### ISSUE TITLE
ActionView Error undefined method `[]'

### ISSUE THREAD

**Issue by djmacleo** [jgraichen/redmine_dashboard#100]
Hello,
I've been trying to get this plugin working for a couple hours now. My production.log file has the following error when I click on the Dashboard tab:
```
ActionView::Template::Error (undefined method '[]' for #<RdbTaskboard:0x3fb55a8>):
1: <% unless User.current.login == '' %>
2:   <% unless @board.nil? || @board[:id].nil? || @topic.nil? || @topic.id.nil? %>
3:     <div id="vote" class="vote-area" data-board="<%=@board[:id] %>" data-topic="<%=@topic.id%>">
4:         <div><a class="vote-button" href="#" data-point="1">â–²</a></div>
5:         <div class="vote-point">-</div>
  lib/redmine/hook.rb:119:in 'block (2 levels) in render_on'
  lib/redmine/hook.rb:117:in 'map'
  lib/redmine/hook.rb:117:in 'block in render_on'
  lib/redmine/hook.rb:61:in 'block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in 'each'
  lib/redmine/hook.rb:61:in 'block in call_hook'
  lib/redmine/hook.rb:58:in 'tap'
  lib/redmine/hook.rb:58:in 'call_hook'
  lib/redmine/hook.rb:167:in 'call_hook'
  app/views/layouts/base.html.erb:59:in '_app_views_layouts_base_html_erb__1012775632_33812244'
```
*I edited the text above to make it format a little better, but you get the idea.

I'm using Redmine 3.0.3.stable and here's a summary of the gems I've bundled with redmine:
Using rake 10.4.2
Using i18n 0.7.0
Using json 1.8.3
Using minitest 5.7.0
Using thread_safe 0.3.5
Using tzinfo 1.2.2
Using activesupport 4.2.1
Using builder 3.2.2
Using erubis 2.7.0
Using mini_portile 0.6.2
Using nokogiri 1.6.6.2
Using rails-deprecated_sanitizer 1.0.3
Using rails-dom-testing 1.0.6
Using loofah 2.0.2
Using rails-html-sanitizer 1.0.2
Using actionview 4.2.1
Using rack 1.6.4
Using rack-test 0.6.3
Using actionpack 4.2.1
Using globalid 0.3.5
Using activejob 4.2.1
Using mime-types 2.6.1
Using mail 2.6.3
Using actionmailer 4.2.1
Using actionpack-action_caching 1.1.1
Using actionpack-xml_parser 1.0.2
Using activemodel 4.2.1
Using arel 6.0.0
Using activerecord 4.2.1
Using addressable 2.3.8
Using bundler 1.10.5
Using climate_control 0.0.3
Using cocaine 0.5.7
Using coderay 1.1.0
Using colorize 0.7.7
Using css_parser 1.3.6
Using tilt 1.4.1
Using haml 4.0.6
Using htmlentities 4.3.3
Using icalendar 2.3.0
Using thor 0.19.1
Using railties 4.2.1
Using jquery-rails 3.1.3
Using kaminari 0.16.3
Using multi_json 1.11.1
Using mysql2 0.3.18
Using net-ldap 0.3.1
Using pandoc-ruby 1.0.0
Using paperclip 4.2.4
Using premailer 1.8.4
Using premailer-rails 1.8.2
Using protected_attributes 1.0.9
Using sprockets 3.2.0
Using sprockets-rails 2.3.1
Using rails 4.2.1
Using prototype-rails 4.0.0 from git://github.com/rails/prototype-rails.git (at 4.2)
Using ruby-openid 2.3.0
Using rack-openid 1.4.2
Using rack-raw-upload 1.1.1
Using rbpdf 1.18.5
Using redcarpet 3.1.2
Using request_store 1.0.5
Using sass 3.4.15
Using sass-rails 5.0.3
Using rich 1.4.8 from https://github.com/a-ono/rich.git (at master)
Using rmagick 2.13.4
Using tzinfo-data 1.2015.5

Any ideas? 

Thanks in advance,
Dave

**Comment by djmacleo** [comment]
Oh and I guess I should have mentioned that redmine is displaying a 500 error:

**Internal error**

An error occurred on the page you were trying to access.
If you continue to experience problems please contact your Redmine administrator for assistance.

If you are the Redmine administrator, check your log files for details about the error.


Sorry about that, I've been staring at logs so long I forgot where the issue started he he

**Comment by jgraichen** [comment]
You are probably using another plugin colliding with Redmine Dashboard. Can you provide a plugin list of you're installed plugins?

**Comment by djmacleo** [comment]
Hi @jgraichen,
Yes, sorry I should have mentioned that. I've only been running this for about two weeks now, so I'm still getting used to all the interoperability issues between plugins. Basically, I installed as many I thought might be useful for my team, though I will admit it's quite a few:


Advanced roadmap & milestones plugin (2.4.2)
https://github.com/ekylibre/redmine_advanced_roadmap_v2

Gantt Menu Link plugin (0.1.1)
https://github.com/mauricio-camayo/redmine-gantt-menu-link

Issue To-do Lists Plugin (1.0.1)
https://github.com/Canidas/issue_todo_lists

Progressive Projects List plugin (2.0.1)
http://stgeneral.github.io/redmine-progressive-projects-list/

Redcase (0.2)


Redmine Add to Calendar (0.0.2)
https://github.com/hidakatsuya/redmine_add_to_calendar

Redmine Agile plugin (Light version) (1.3.9)
http://redminecrm.com

Redmine Auto Done 100% (0.0.1)

Redmine Checklists plugin (Light version) (3.1.1)
http://redminecrm.com

Redmine CKEditor plugin (1.1.0)
http://github.com/a-ono/redmine_ckeditor

Redmine Code Review plugin (0.7.0)
http://www.r-labs.org/projects/show/codereview

Redmine Dashboard plugin (2.5.0)
https://github.com/jgraichen/redmine_dashboard

Project Search Box Plugin (0.0.3)
https://github.com/ries-tech/redmine_improved_searchbox

Redmine Mail Reminder plugin (3.0.0.0001)
https://github.com/Hopebaytech/redmine_mail_reminder

Redmine Mentions (0.0.1)
https://github.com/arkhitech/redmine_mentions

Redmine per project formatting plugin ()0.0.4)
https://github.com/a-ono/redmine_per_project_formatting

Redmine Planning plugin (0.7.6)
https://github.com/MadEgg/redmine_planning

Redmine Theme Changer plugin (0.2.0)
http://www.r-labs.org/projects/themechanger

Redmine Vote plugin (1.2.2)
http://github.com/jongha/redmine_vote

Redrisk plugin (1.0.1)
https://github.com/rolesoft/redrisk

Scrum Redmine plugin (0.11.1)
https://redmine.ociotec.com/projects/redmine-plugin-scrum

Redmine Status Button plugin (0.1.0)


The CKEditor plugin seems to have issues with some text fields, so I've defaulted it to only be used for the wiki pages at the moment. I should also mention this is a Windows 7 computer and I'm using Ruby version 1.9.3

Hopefully this is enough to go on, but let me know if there's something else I can provide.

I really appreciate the help!

Cheers,
Dave

**Comment by jgraichen** [comment]
Thanks. There is a collision with [Redmine Vote plugin (1.2.2)](http://github.com/jongha/redmine_vote) that is injecting code in *every* page. Removing it should resolve the issue. A fix should probably be implemented in the vote plugin. If you create an issue there I will provide additional technical information there as soon as I have some time for some more investigation.

**Comment by djmacleo** [comment]
Yup, that did the trick.

Thanks very much!
