### ISSUE TITLE
Problem with version 2.6.1

### ISSUE THREAD

**Issue by monavie1989** [jgraichen/redmine_dashboard#101]
I was install redmine version 3.0.4
I install redmine dashboard 2.6.1, after install complete I checking in setting->plugins and the plugin show version 2.5.0. I was click Check for updates but version still 2.5.0.
Please check attach to show detail.
I go to one Project to demo but in menu project page not show tab Dashboard.
May be plugin not running in version 3.0.4. Some body can help me solve this issue ?
Thanks.
![redmine_daskboard 2_6_1](https://cloud.githubusercontent.com/assets/6936681/8748480/fccf72c0-2cc4-11e5-97ca-87469f5e9b46.jpg)
![redmine_daskboard 2_6_1_image1](https://cloud.githubusercontent.com/assets/6936681/8748481/fcd43562-2cc4-11e5-8faf-8cd85e92b161.jpg)

**Comment by jgraichen** [comment]
You need to give the "View Dashboard" and "Edit Dashboard" permissions to roles. They are located in the administration area.
![ed88c235d392f2](https://cloud.githubusercontent.com/assets/800848/8767216/8fc46374-2e55-11e5-9682-59af408f7a6e.png)

**Comment by monavie1989** [comment]
Thank you for the quick response.

On Mon, Jul 20, 2015 at 1:34 AM, Jan Graichen <notifications@github.com>
wrote:

> Closed #101 <https://github.com/jgraichen/redmine_dashboard/issues/101>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jgraichen/redmine_dashboard/issues/101#event-359511253>
> .
>



-- 
*Name:* Nguyễn Như Quyết .
*Address:* Chương Mỹ - Hà Nội.
*Phone:* 01656 223 510.
*Email:* nguyenhuquyet@gmail.com.
*Webiste: *http://site4company.com <http://aoe.tzongreen.com/>
*Job:* Programmer.
