### ISSUE TITLE
Errors installing 2.7.0 on Redmine 3.0.4

### ISSUE THREAD

**Issue by ronaldcs** [jgraichen/redmine_dashboard#105]
Hi,

I get the following when trying to upgrade the dashboard to 2.7.0:

```
You have requested:
  rspec ~> 3.0

The bundle currently has rspec locked at 2.99.0.
Try running `bundle update rspec`
```
Not an expert, but looking at the Gemfile.lock file I see:

```
    rspec (2.99.0)
      rspec-core (~> 2.99.0)
      rspec-expectations (~> 2.99.0)
      rspec-mocks (~> 2.99.0)
    rspec-collection_matchers (1.1.2)
      rspec-expectations (>= 2.99.0.beta1)
    rspec-core (2.99.2)
    rspec-expectations (2.99.2)
      diff-lcs (>= 1.1.3, < 2.0)
    rspec-mocks (2.99.4)
    rspec-rails (2.99.0)
      actionpack (>= 3.0)
      activemodel (>= 3.0)
      activesupport (>= 3.0)
      railties (>= 3.0)
      rspec-collection_matchers
      rspec-core (~> 2.99.0)
      rspec-expectations (~> 2.99.0)
      rspec-mocks (~> 2.99.0)
```

I've tried deleting the Gemfile.lock file, which results in a successful install, but an Internal Error when accessing the Dashboard after doing `bundle install --without development test`. Any suggestions?

Thanks!

**Comment by jgraichen** [comment]
`bundle install --without development test` is correct. The internal error may have another cause. Can please provide some log from the error as well as other plugins you're using and their versions?

**Comment by jasonfharris** [comment]
For what it is worth, the dashboard plugin seems to work for me on my one-click ubuntu install from digital ocean. I updgraded my install to redmine 3.1.0.stable.

**Comment by ronaldcs** [comment]
Absolutely...we're on a VM so I rollbacked to the snapshot when I got the error. I'll provide logs when I get a chance off-hours.

Thanks guys,

Ron

**Comment by xJom** [comment]
I am sure I wrote bundle install --without development test, but it seemed to ignore that for this particular plugin. I had to remove the development and test sections from the Gemfile, to be able to install, else I got a few strange errors, and this rspec clash was one of them.
