### ISSUE TITLE
Just installed this into 2.6.6 and get empty page

### ISSUE THREAD

**Issue by Bodge-IT** [jgraichen/redmine_dashboard#107]
No dash, no options or buttons, just a menu option.

**Comment by jgraichen** [comment]
How did you install it? Make sure you installed stable version v2. Any log entries? Any errors?

**Comment by Bodge-IT** [comment]
Sorry, I didn't have time to look into that at the time.  I had hoped others might have come accross the issue.  FWiW I'm running RM2.6.6 and cloned the plugin through git.  

I found this positive note in the log:
<pre>Redirected to http://rm.barclayworks.com/redmine/rdb/dashboards/1
Completed 302 Found in 494.7ms (ActiveRecord: 33.2ms)
Started GET "/redmine/rdb/dashboards/1" for 87.81.134.171 at 2015-08-20 19:01:18 +0000
Processing by RdbController#show as HTML
  Parameters: {"id"=>"1"}
  Current user: bw-admin (id=3)
  Rendered plugins/redmine_dashboard/app/views/rdb/show.html.slim within layouts/base (97.2ms)
  Rendered plugins/redmine_code_review/app/views/code_review/_html_header.html.erb (1.7ms)
  Rendered inline template (0.9ms)
  Rendered plugins/clipboard_image_paste/app/views/clipboard_image_paste/_headers.html.erb (1.3ms)
  Rendered plugins/redmine_tweaks/app/views/application/_global_header.erb (51.3ms)
  Rendered plugins/redmine_planning/app/views/hooks/_planning_scripts.html.erb (0.5ms)
  Rendered plugins/redmine_tweaks/app/views/application/_global_content.erb (0.1ms)
  Rendered plugins/redmine_code_review/app/views/code_review/_body_bottom.html.erb (0.1ms)
  Rendered plugins/clipboard_image_paste/app/views/clipboard_image_paste/_add_form.html.erb (3.5ms)
  Rendered plugins/redmine_tweaks/app/views/application/_global_footer.erb (0.1ms)
Completed 200 OK in 450.8ms (Views: 430.8ms | ActiveRecord: 5.2ms)
Started GET "/redmine/plugin_assets/redmine_dashboard/main.js" for 87.81.134.171 at 2015-08-20 19:01:19 +0000</pre>

Followed, on a less positive note, by:
<pre>ActionController::RoutingError (No route matches [GET] "/plugin_assets/redmine_dashboard/main.js"):
  actionpack (3.2.22) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  actionpack (3.2.22) lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
  railties (3.2.22) lib/rails/rack/logger.rb:32:in `call_app'
  railties (3.2.22) lib/rails/rack/logger.rb:16:in `block in call'
  activesupport (3.2.22) lib/active_support/tagged_logging.rb:22:in `tagged'
  railties (3.2.22) lib/rails/rack/logger.rb:16:in `call'
  actionpack (3.2.22) lib/action_dispatch/middleware/request_id.rb:22:in `call'
  rack (1.4.7) lib/rack/methodoverride.rb:21:in `call'
  rack (1.4.7) lib/rack/runtime.rb:17:in `call'
  activesupport (3.2.22) lib/active_support/cache/strategy/local_cache.rb:72:in `call'
  rack (1.4.7) lib/rack/lock.rb:15:in `call'
  actionpack (3.2.22) lib/action_dispatch/middleware/static.rb:83:in `call'
  rack-cache (1.2) lib/rack/cache/context.rb:136:in `forward'
  rack-cache (1.2) lib/rack/cache/context.rb:245:in `fetch'
  rack-cache (1.2) lib/rack/cache/context.rb:185:in `lookup'
  rack-cache (1.2) lib/rack/cache/context.rb:66:in `call!'
  rack-cache (1.2) lib/rack/cache/context.rb:51:in `call'
  railties (3.2.22) lib/rails/engine.rb:484:in `call'
  railties (3.2.22) lib/rails/application.rb:231:in `call'
  railties (3.2.22) lib/rails/railtie/configurable.rb:30:in `method_missing'
  rack (1.4.7) lib/rack/builder.rb:134:in `call'
  rack (1.4.7) lib/rack/urlmap.rb:64:in `block in call'
  rack (1.4.7) lib/rack/urlmap.rb:49:in `each'
  rack (1.4.7) lib/rack/urlmap.rb:49:in `call'
  passenger (4.0.25) lib/phusion_passenger/rack/thread_handler_extension.rb:77:in `process_request'
  passenger (4.0.25) lib/phusion_passenger/request_handler/thread_handler.rb:140:in `accept_and_process_next_request'
  passenger (4.0.25) lib/phusion_passenger/request_handler/thread_handler.rb:108:in `main_loop'
  passenger (4.0.25) lib/phusion_passenger/request_handler.rb:441:in `block (3 levels) in start_threads'
</pre>

Followed up with:
<pre>ActionController::RoutingError (No route matches [GET] "/plugin_assets/redmine_dashboard/main.css"):
> Stuff
Started GET "/redmine/plugin_assets/redmine_dashboard/main.css" for 87.81.134.171 at 2015-08-20 19:01:20 +0000
> Stuff</pre>

I hope this provides clarity...routing issues sound like missing files?
This was the first entry I could find in logs.

**Comment by jgraichen** [comment]
You installed the development version from the master branch but did not follow the installation guide. A simple clone is *not* enough for v3.0-dev.

I assume you want the current stable version 2.7.0 of Redmine Dashboard. Please do follow the [installation instruction for v2](https://github.com/jgraichen/redmine_dashboard/tree/stable-v2#install).

If you really want to run the incomplete, development version you must follow the Readme and compile yourself.

P.S. You may run v2 via git by `git checkout v2.7.0`, but this *will not* work for v3+. Therefore I recommend installing via archive only.

**Comment by Bodge-IT** [comment]
Hi John,
Thanks for the heads up and sorry for the distraction.
I’ll give it another as it looks an awesome plugin.

Thanks
Gary
