### ISSUE TITLE
Unreadable dashboard when there are many statuses types

### ISSUE THREAD

**Issue by Pierstoval** [jgraichen/redmine_dashboard#108]
Hi, I have a big redmine app where I have maaaany different statuses for each tracker, so some status are not used by some trackers and vice-versa.

This results in an unreadable dashboard :disappointed: 
![capture d ecran 2015-08-24 a 13 11 24](https://cloud.githubusercontent.com/assets/3369266/9438834/dbbe2bb6-4a61-11e5-8dc4-17f880fb61c8.png)

I know we can edit this with the `Options` sub-menu on the top right, but as there are MANY statuses, it's quite long and boring to do this, especially for each project...
And it's very long, I don't know for other users, but the action of filtering something can take up to 10 seconds, whereas the rest of the application is usually fast... :question: 

Is it possible to filter the statuses to get only the ones used by the filtered tracker? 
Or find a solution for the status filtering to be faster?
When filtering for one tracker, it could be better to view only the statuses that are available to this tracker.
With this, I'd get a clear view of all my different workflows directly.

**Comment by xJom** [comment]
Showing only the statuses allowed for the selected tracker would be very useful for us, too.

**Comment by samhe** [comment]
+1

can we save the dashboard's default criteria per project?  just like the custom query in issue list ?

**Comment by jgraichen** [comment]
@Pierstoval When you moved an issue to an "invalid" status, were you an administrator?

**Comment by Pierstoval** [comment]
> @Pierstoval When you moved an issue to an "invalid" status, were you an administrator?

Yes, I was. Do you think it might be different for non-admins?

**Comment by jgraichen** [comment]
Yes. Workflows were only enforced for non-administrators. This code has been removed in [2.11.0.rc1](https://github.com/jgraichen/redmine_dashboard/discussions/149) along with many other fixes and additions. Starting with 2.11.0, workflows will be enforced for all users. It would be awesome if you can test 2.11.rc1 and report on your findings!
