### ISSUE TITLE
rspec 2.0 requested, 3.3.0 installed?

### ISSUE THREAD

**Issue by mwalimu82** [jgraichen/redmine_dashboard#110]
Hi, 
when I try to install the 2.7.0 dashboard plugin on my xubuntu machine,
bundle install --without development test
gives me:

You have requested:
  rspec ~> 2.0
The bundle currently has rspec locked at 3.3.0.
Try running `bundle update rspec`

I understand that I have installed 3.3.0 but it is recognized as been not ~> 2.0.

Do I understand this wrong (am German) or does this realy not make sense? What to do?
Regards

**Comment by jgraichen** [comment]
The dependency `~> 2.0` is short for `>= 2.0, < 3` (aka. `2.x`). It aborts because `3.3.0` is not `2.x`.

You can probably try to just delete `Gemfile.lock` and run `bundle install --without development test` again. It will resolve the dependencies again without preliminaries.
