### ISSUE TITLE
LoadError: cannot load such file -- haml

### ISSUE THREAD

**Issue by mbrownnycnyc** [jgraichen/redmine_dashboard#112]
Hello,

I am receiving the error when I attempt to perform the plugin installation:

    C:\Bitnami\redmine-3.1.0-0\apps\redmine\htdocs\plugins>bundle exec rake redmine:plugins:migrate RAILS_ENV=production
    Warning: this Gemfile contains multiple primary sources. Using `source` more than once without a block is a security ris
    k, and may result in installing unexpected gems. To resolve this warning, use a block to indicate which gems should come
     from the secondary source. To upgrade this warning to an error, run `bundle config disable_multisource true`.
    (in C:/Bitnami/redmine-3.1.0-0/apps/redmine/htdocs)
    DL is deprecated, please use Fiddle
    rake aborted!
    LoadError: cannot load such file -- haml
    C:/Bitnami/redmine-3.1.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.3/lib/active_support/depe
    ndencies.rb:274:in `require'
    C:/Bitnami/redmine-3.1.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.3/lib/active_support/depe
    ndencies.rb:274:in `block in require'
    C:/Bitnami/redmine-3.1.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.3/lib/active_support/depe
    ndencies.rb:240:in `load_dependency'
    C:/Bitnami/redmine-3.1.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.3/lib/active_support/depe
    ndencies.rb:274:in `require'
    C:/Bitnami/redmine-3.1.0-0/apps/redmine/htdocs/plugins/redmine_dashboard/init.rb:2:in `<top (required)>'
    C:/Bitnami/redmine-3.1.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.3/lib/active_support/depe
    ndencies.rb:274:in `require'
    C:/Bitnami/redmine-3.1.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.3/lib/active_support/depe
    ndencies.rb:274:in `block in require'
    C:/Bitnami/redmine-3.1.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.3/lib/active_support/depe
    ndencies.rb:240:in `load_dependency'
    C:/Bitnami/redmine-3.1.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.3/lib/active_support/depe
    ndencies.rb:274:in `require'
    C:/Bitnami/redmine-3.1.0-0/apps/redmine/htdocs/lib/redmine/plugin.rb:155:in `block in load'
    C:/Bitnami/redmine-3.1.0-0/apps/redmine/htdocs/lib/redmine/plugin.rb:146:in `each'
    C:/Bitnami/redmine-3.1.0-0/apps/redmine/htdocs/lib/redmine/plugin.rb:146:in `load'
    C:/Bitnami/redmine-3.1.0-0/apps/redmine/htdocs/config/initializers/30-redmine.rb:21:in `<top (required)>'
    C:/Bitnami/redmine-3.1.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.3/lib/active_support/depe
    ndencies.rb:268:in `load'
    C:/Bitnami/redmine-3.1.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.3/lib/active_support/depe
    ndencies.rb:268:in `block in load'
    C:/Bitnami/redmine-3.1.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.3/lib/active_support/depe
    ndencies.rb:240:in `load_dependency'
    C:/Bitnami/redmine-3.1.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.3/lib/active_support/depe
    ndencies.rb:268:in `load'
    C:/Bitnami/redmine-3.1.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/railties-4.2.3/lib/rails/engine.rb:652:in `
    block in load_config_initializer'
    C:/Bitnami/redmine-3.1.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.3/lib/active_support/noti
    fications.rb:166:in `instrument'
    C:/Bitnami/redmine-3.1.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/railties-4.2.3/lib/rails/engine.rb:651:in `
    load_config_initializer'
    C:/Bitnami/redmine-3.1.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/railties-4.2.3/lib/rails/engine.rb:616:in `
    block (2 levels) in <class:Engine>'
    C:/Bitnami/redmine-3.1.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/railties-4.2.3/lib/rails/engine.rb:615:in `
    each'
    C:/Bitnami/redmine-3.1.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/railties-4.2.3/lib/rails/engine.rb:615:in `
    block in <class:Engine>'
    C:/Bitnami/redmine-3.1.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/railties-4.2.3/lib/rails/initializable.rb:3
    0:in `instance_exec'
    C:/Bitnami/redmine-3.1.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/railties-4.2.3/lib/rails/initializable.rb:3
    0:in `run'
    C:/Bitnami/redmine-3.1.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/railties-4.2.3/lib/rails/initializable.rb:5
    5:in `block in run_initializers'
    C:/Bitnami/redmine-3.1.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/railties-4.2.3/lib/rails/initializable.rb:4
    4:in `each'
    C:/Bitnami/redmine-3.1.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/railties-4.2.3/lib/rails/initializable.rb:4
    4:in `tsort_each_child'
    C:/Bitnami/redmine-3.1.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/railties-4.2.3/lib/rails/initializable.rb:5
    4:in `run_initializers'
    C:/Bitnami/redmine-3.1.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/railties-4.2.3/lib/rails/application.rb:352
    :in `initialize!'
    C:/Bitnami/redmine-3.1.0-0/apps/redmine/htdocs/config/environment.rb:14:in `<top (required)>'
    C:/Bitnami/redmine-3.1.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.3/lib/active_support/depe
    ndencies.rb:274:in `require'
    C:/Bitnami/redmine-3.1.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.3/lib/active_support/depe
    ndencies.rb:274:in `block in require'
    C:/Bitnami/redmine-3.1.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.3/lib/active_support/depe
    ndencies.rb:240:in `load_dependency'
    C:/Bitnami/redmine-3.1.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.3/lib/active_support/depe
    ndencies.rb:274:in `require'
    C:/Bitnami/redmine-3.1.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/railties-4.2.3/lib/rails/application.rb:328
    :in `require_environment!'
    C:/Bitnami/redmine-3.1.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/railties-4.2.3/lib/rails/application.rb:457
    :in `block in run_tasks_blocks'
    Tasks: TOP => redmine:plugins:migrate => environment
    (See full trace by running task with --trace)

However, I have haml installed:

    C:\Bitnami\redmine-3.1.0-0\apps\redmine\htdocs\plugins>irb
    irb(main):001:0> require 'haml'
    => true

Why would this be occurring?

Thanks,

Matt

**Comment by jgraichen** [comment]
Please see #24 or #58 and [README point 3 note for appliances](https://github.com/jgraichen/redmine_dashboard/tree/stable-v2#manual).

**Comment by mbrownnycnyc** [comment]
Thank you!

The following resolved issues as stated in #24.

      "C:\Bitnami\redmine-3.1.0-0\use_redmine.bat"
      cd C:\Bitnami\redmine-3.1.0-0\apps\redmine\htdocs\plugins
      bundle install --path vendor/bundle --no-deployment
