### ISSUE TITLE
Dashboard module not visible for non-administrators

### ISSUE THREAD

**Issue by mbrownnycnyc** [jgraichen/redmine_dashboard#113]
For Managers on Projects that are not redmine administrators, and it doesn't appear that the Dashboard tab/module is visible to them.

Is this intended?  Can it be modified?

**Comment by jgraichen** [comment]
You have to assign the 'View dashboard' and 'Edit dashboard' permissions to the respective roles. You can find them in redmine's permission editor in the administration area.
