### ISSUE TITLE
Installation on 3.2 version

### ISSUE THREAD

**Issue by meetdileep** [jgraichen/redmine_dashboard#118]
Hi,

I tried to install dashboard in 3.2 version and It got installed without throwing any errors and it was adding to Project Menus even. But nothing is displaying when we click on that. Any suggestion or guidance on this front.

Thanks in advance.
Dileep

**Comment by jgraichen** [comment]
I assume you mean Redmine 3.2.

Please see #107. Otherwise please post logs, error messages, installations details and describe your installation process.

**Comment by SergeyBear** [comment]
Just installed latest redmine_dashboard 2 on Redmine 3.2.0 - work like a charm!
Awsome dashboard!!!
