### ISSUE TITLE
not support redmine 3.2.X?

### ISSUE THREAD

**Issue by archonwang** [jgraichen/redmine_dashboard#124]
I used redmine 3.2.1 and I have install the plugin. but it could not use when I open the dashboard.

error logs

> Started GET "/plugin_assets/redmine_dashboard/main.css" for 192.168.60.239 at 2016-04-26 20:47:01 +0800
> 
> ActionController::RoutingError (No route matches [GET] "/plugin_assets/redmine_dashboard/main.css"):
>   actionpack (4.2.5.2) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
>   actionpack (4.2.5.2) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
>   railties (4.2.5.2) lib/rails/rack/logger.rb:38:in `call_app'
>   railties (4.2.5.2) lib/rails/rack/logger.rb:20:in `block in call'
>   activesupport (4.2.5.2) lib/active_support/tagged_logging.rb:68:in `block in tagged'
>   activesupport (4.2.5.2) lib/active_support/tagged_logging.rb:26:in `tagged'
>   activesupport (4.2.5.2) lib/active_support/tagged_logging.rb:68:in `tagged'
>   railties (4.2.5.2) lib/rails/rack/logger.rb:20:in `call'
>   actionpack (4.2.5.2) lib/action_dispatch/middleware/request_id.rb:21:in `call'
>   rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
>   rack (1.6.4) lib/rack/runtime.rb:18:in `call'
>   activesupport (4.2.5.2) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
>   actionpack (4.2.5.2) lib/action_dispatch/middleware/static.rb:116:in `call'
>   rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
>   railties (4.2.5.2) lib/rails/engine.rb:518:in `call'
>   railties (4.2.5.2) lib/rails/application.rb:165:in `call'
>   railties (4.2.5.2) lib/rails/railtie.rb:194:in `public_send'
>   railties (4.2.5.2) lib/rails/railtie.rb:194:in `method_missing'
>   thin (1.6.4) lib/thin/connection.rb:86:in `block in pre_process'
>   thin (1.6.4) lib/thin/connection.rb:84:in `catch'
>   thin (1.6.4) lib/thin/connection.rb:84:in `pre_process'
>   thin (1.6.4) lib/thin/connection.rb:53:in `process'
>   thin (1.6.4) lib/thin/connection.rb:39:in `receive_data'
>   eventmachine (1.2.0.1) lib/eventmachine.rb:194:in `run_machine'
>   eventmachine (1.2.0.1) lib/eventmachine.rb:194:in `run'
>   thin (1.6.4) lib/thin/backends/base.rb:73:in `start'
>   thin (1.6.4) lib/thin/server.rb:162:in `start'
>   thin (1.6.4) lib/thin/controllers/controller.rb:87:in `start'
>   thin (1.6.4) lib/thin/runner.rb:200:in `run_command'
>   thin (1.6.4) lib/thin/runner.rb:156:in `run!'
>   thin (1.6.4) bin/thin:6:in `<top (required)>'
>   /usr/local/rvm/gems/ruby-2.2.4@newgemset/bin/thin:23:in `load'
>   /usr/local/rvm/gems/ruby-2.2.4@newgemset/bin/thin:23:in `<main>'
> 
> 
> Started GET "/plugin_assets/redmine_dashboard/main.js" for 192.168.60.239 at 2016-04-26 20:47:01 +0800
> 
> ActionController::RoutingError (No route matches [GET] "/plugin_assets/redmine_dashboard/main.js"):
>   actionpack (4.2.5.2) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
>   actionpack (4.2.5.2) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
>   railties (4.2.5.2) lib/rails/rack/logger.rb:38:in `call_app'
>   railties (4.2.5.2) lib/rails/rack/logger.rb:20:in `block in call'
>   activesupport (4.2.5.2) lib/active_support/tagged_logging.rb:68:in `block in tagged'
>   activesupport (4.2.5.2) lib/active_support/tagged_logging.rb:26:in `tagged'
>   activesupport (4.2.5.2) lib/active_support/tagged_logging.rb:68:in `tagged'
>   railties (4.2.5.2) lib/rails/rack/logger.rb:20:in `call'
>   actionpack (4.2.5.2) lib/action_dispatch/middleware/request_id.rb:21:in `call'
>   rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
>   rack (1.6.4) lib/rack/runtime.rb:18:in `call'
>   activesupport (4.2.5.2) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
>   actionpack (4.2.5.2) lib/action_dispatch/middleware/static.rb:116:in `call'
>   rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
>   railties (4.2.5.2) lib/rails/engine.rb:518:in `call'
>   railties (4.2.5.2) lib/rails/application.rb:165:in `call'
>   railties (4.2.5.2) lib/rails/railtie.rb:194:in `public_send'
>   railties (4.2.5.2) lib/rails/railtie.rb:194:in `method_missing'
>   thin (1.6.4) lib/thin/connection.rb:86:in `block in pre_process'
>   thin (1.6.4) lib/thin/connection.rb:84:in `catch'
>   thin (1.6.4) lib/thin/connection.rb:84:in `pre_process'
>   thin (1.6.4) lib/thin/connection.rb:53:in `process'
>   thin (1.6.4) lib/thin/connection.rb:39:in `receive_data'
>   eventmachine (1.2.0.1) lib/eventmachine.rb:194:in `run_machine'
>   eventmachine (1.2.0.1) lib/eventmachine.rb:194:in `run'
>   thin (1.6.4) lib/thin/backends/base.rb:73:in `start'
>   thin (1.6.4) lib/thin/server.rb:162:in `start'
>   thin (1.6.4) lib/thin/controllers/controller.rb:87:in `start'
>   thin (1.6.4) lib/thin/runner.rb:200:in `run_command'
>   thin (1.6.4) lib/thin/runner.rb:156:in `run!'
>   thin (1.6.4) bin/thin:6:in `<top (required)>'
>   /usr/local/rvm/gems/ruby-2.2.4@newgemset/bin/thin:23:in `load'
>   /usr/local/rvm/gems/ruby-2.2.4@newgemset/bin/thin:23:in `<main>'

**Comment by jgraichen** [comment]
Please see [#107](https://github.com/jgraichen/redmine_dashboard/issues/107#issuecomment-135351883).

**Comment by archonwang** [comment]
thanks. I have change to branch stable-v2.
