### ISSUE TITLE
redmine_dashboard_linked for link to plugin_assets ?

### ISSUE THREAD

**Issue by klyonrad** [jgraichen/redmine_dashboard#126]
Regarding v2.7.1

Why do you reference the plugin_assets to `redmine_dashboard_linked` for the development mode? If that is still required then workarounds for that should be noted in the installation instructions

**Comment by jgraichen** [comment]
I have the plugin assets directory symlinked for development. This way can regenerate stylesheets and javascript without having to restart redmine to copy the new assets. This is not needed in any way for production so it is not mentioned the installation instructions. Do you want to develop on redmine_dashboard or trying to setup a kind of test setup running in development environment?

**Comment by klyonrad** [comment]
Ah, I suspected something like that :)

> trying to setup a kind of test setup running in development environment?

Yes, I was doing that

**Comment by jgraichen** [comment]
I cannot recommend that. Redmine, Rails, and plugins will behave different than in production environment. The Rails environment should primary used to differ between developing the app (hacking app code) vs running the application. Demo setups etc. should always use the production Rails environment.
