### ISSUE TITLE
Dashboard not visible in main menu.

### ISSUE THREAD

**Issue by ibndooom** [jgraichen/redmine_dashboard#129]
Hello, i have some strange trouble.
I have installed redmine_dashboard **2.7.1** on dockerized redmine **3.2.0** 
Plugin visible on url _/admin/plugins_, i see settings in "Roles and permissions", but there are no "Dashboard" item in main menu. When i try url _/rdb/dashboards_ it return 404.

Could you please help me with this?

**Comment by jgraichen** [comment]
You may have to enable the dashboard module for your projects:

![20161201019627fbbb6a](https://cloud.githubusercontent.com/assets/800848/20795344/fcf1c454-b7d0-11e6-8fc2-21e7f253ce6b.png)

**Comment by ibndooom** [comment]
Hi, have enabled it, but it looks strange
![](http://image.prntscr.com/image/9bbba4b7726a475da1e22ca6fcaac95b.png)

When i click on this link, i see **404**

May be it's important, i have installed **3.0alpha** earlier, but then i removed it and install **2.7.1**

**Comment by ibndooom** [comment]
Thanks, it works :)
my bad
