### ISSUE TITLE
Question: Plugin Testable Non-Destructive?

### ISSUE THREAD

**Issue by mr-gosh** [jgraichen/redmine_dashboard#131]
Is this plugin tinkering with the database or can it be tested and purged without a problem?
We had problems with getting rid of plugins that were not compatible with the latest Redmine Versions anymore.

**Comment by jgraichen** [comment]
Redmine Dashboard (2.x) does not change the database. It actually has no persistent state at all. Removing all plugin files will remove all traces of the plugin (except for cookie data in the browser session).

**Comment by mr-gosh** [comment]
perfect - THX!

For the record - you should still have Backups up and running if you test Plugins... ;)
