### ISSUE TITLE
main.css 404 & Rdb is not defined

### ISSUE THREAD

**Issue by bhavinsa** [jgraichen/redmine_dashboard#137]
I have install the redmine_dashboard, when I do below command it give me error like 

$ make css js # development
$ make min # production

Error that I am facing is:    `make: *** No rule to make target 'css'.  Stop.`

at client side, in console I am facing this:

`GET http://18.237.50.56/redmine/plugin_assets/redmine_dashboard/main.css 404 (Not Found) 
1:105 Uncaught ReferenceError: Rdb is not defined     at 1:105 (anonymous) @ 1:105`

In redmine, Dashboard tab appear, but when I click on it, it will show blank page.

Could you please assist.

**Comment by jgraichen** [comment]
Please note that the development v3 is not ready for production use. Please follow the installation guide for v2: https://github.com/jgraichen/redmine_dashboard/blob/stable-v2/README.md#install
