### ISSUE TITLE
Redmine Dashboard isssue 

### ISSUE THREAD

**Issue by sarmani147** [jgraichen/redmine_dashboard#146]
![dashboard](https://user-images.githubusercontent.com/84909724/119816664-9b3d5c00-bf0a-11eb-8b96-70f6c6ef356f.PNG)
Hi,

I have a Redmine opensource ticketing system running on ubuntu 20.04 and facing an issue with Redmine Dashboard, it is working on CentOS.

Not sure, if this issue is caused due to the Linux flavor difference. error screenshot attached. Any solution is appreciated!!

**Comment by contentadore** [comment]
I have the same error with Redmine 4.1.1 (Debian 10)

**Comment by jgraichen** [comment]
How did you install the plugin? The screenshot indicates your server isn't shipping the JavaScript and CSS files bundled with the plugin. Please check your server configuration and browser console for errors.

**Comment by jgraichen** [comment]
Please make sure your Redmine is correctly installed, especially the directory permissions for `public/`. Redmine will copy assets (e.g. JavaScript) from plugins there, if they are missing, the dashboard will not work correctly.
