### ISSUE TITLE
Project list on left side

### ISSUE THREAD

**Issue by ChZiegelt** [jgraichen/redmine_dashboard#2]
Dear jgrainchen,

I realy like your plugin for redmine.
what I'd like to see is a project list on the left side of the dashboard.
That way I could easily switch between different projects (we've got many of them)

It would be fine, if the project list was hideable.

The second request would be: optional displaying tickets of subprojects as well as tickets by the selected project.

Thanks in advance

**Comment by jgraichen** [comment]
Recent Redmine versions do not switch to the main page when switching the project using the quick switch. I'll close this, unless that behavior isn't enough.
