### ISSUE TITLE
Support Redmine v5.0

### ISSUE THREAD

**Issue by enzofoucaud** [jgraichen/redmine_dashboard#205]
Have you started looking at improving the version?

Redmine 5.0 (will be delivered on 27/03) : https://www.redmine.org/versions/155

**Comment by jgraichen** [comment]
Redmine 5.0 and Ruby 3.0 and 3.1 are supported in [v2.12.0](https://github.com/jgraichen/redmine_dashboard/releases/tag/v2.12.0). Please do test if there are any undiscovered issues, thanks!
