### ISSUE TITLE
Japanese locale missing pluralization key

### ISSUE THREAD

**Issue by jgraichen** [jgraichen/redmine_dashboard#233]
The Japanese locale file is missing a string for the count=1 case: 

```
# config/locales/ja.yml
  rdb_x_issues:
    other: "%{count} 件のチケット"
    one: ?
```

---

After using it, an error may occur when browsing some projects in the following environment.

```
Environment:
  Redmine version                5.0.0.stable.21535
  Ruby version                   3.0.4-p208 (2022-04-12) [x86_64-linux]
  Rails version                  6.1.5
  Environment                    production
  Database adapter               PostgreSQL
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
Redmine settings:
  Redmine theme                  Classic
SCM:
  Subversion                     1.13.0
  Git                            2.25.1
  Filesystem                     
Redmine plugins:
  redmine_dashboard              2.12.1
  redmine_slack                  0.2
  view_customize                 3.0.0
```

■log■

```
App 20861 output: [faa9d299-20b0-4049-acd9-2a5a87a58ace] Processing by RdbTaskboardController#index as JS
App 20861 output: [faa9d299-20b0-4049-acd9-2a5a87a58ace]   Parameters: {"_"=>"1652513841483", "id"=>"signz-for-biz"}
App 20861 output: [faa9d299-20b0-4049-acd9-2a5a87a58ace]   Current user: XXXX (id=1)
App 20861 output: [faa9d299-20b0-4049-acd9-2a5a87a58ace]   Rendered plugins/redmine_dashboard/app/views/rdb_dashboard/index.js.erb (Duration: 29.7ms | Allocations: 11396)
App 20861 output: [faa9d299-20b0-4049-acd9-2a5a87a58ace] Completed 500 Internal Server Error in 46ms (ActiveRecord: 10.2ms | Allocations: 15999)
App 20861 output: [faa9d299-20b0-4049-acd9-2a5a87a58ace]   
App 20861 output: [faa9d299-20b0-4049-acd9-2a5a87a58ace] ActionView::Template::Error (translation data {:other=>"%{count} 件のチケット"} can not be used with :count => 1. key 'one' is missing.):
App 20861 output: [faa9d299-20b0-4049-acd9-2a5a87a58ace]     4:       li.rdb-column class=(column.compact? ? 'rdb-column-compact' : '')
App 20861 output: [faa9d299-20b0-4049-acd9-2a5a87a58ace]     5:         h3 = column.title
App 20861 output: [faa9d299-20b0-4049-acd9-2a5a87a58ace]     6:         - if column.issues.count > 0
App 20861 output: [faa9d299-20b0-4049-acd9-2a5a87a58ace]     7:           span = t :rdb_x_issues, count: column.issues.coun
```

_Originally posted by @kyahagi in https://github.com/jgraichen/redmine_dashboard/discussions/213#discussioncomment-2750089_

**Comment by jgraichen** [comment]
@kyahagi Thanks for reporting!

Can you say if the string "%{count} 件のチケット" needs a different form/term when `count` is `1`? Is "1 件のチケット" correct, or would there be a better term?

**Comment by kyahagi** [comment]
My late reply.
I think it's correct.

**Comment by howtoesc** [comment]
Same issue in chinise

`F, [2022-05-17T00:58:15.363056 #1] FATAL -- :
ActionView::Template::Error (translation data {:other=>"%{count} 问题"} can not be used with :count => 1. key 'one' is missing.):
    4:       li.rdb-column class=(column.compact? ? 'rdb-column-compact' : '')
    5:         h3 = column.title
    6:         - if column.issues.count > 0
    7:           span = t :rdb_x_issues, count: column.issues.count

`

**Comment by jgraichen** [comment]
Thanks! This issue seems to be that Redmine itself does _not_ ship any pluralization rules. Every locale in Redmine only used `one` + `other` with English pluralization rules.

Our translations here are managed on Transifex, that knows and assumes locale-specific pluralization, e.g. only `other` for Japanese and Chinese.

Previously, Redmine Dashboard shipped with correct pluralization rules for all locales, but that broke some Redmine locales (e.g. `ar`). Most of them do not contain the actual needed pluralization fields (e.g. `zero`, `one`, `few`, `many`, `other`) but only `one` and `other`. Pluralization rules always are global in Rails, I cannot easily use them only for Dashboard locales.

I'll see if I can provide a workaround at least for Japanese and Chinese and ask Redmine if they plan to address their issues and provide rules for all.
