### ISSUE TITLE
I wish that, when assigning a task to a subproject they are still shown in the root project.

### ISSUE THREAD

**Issue by ungentilgarcon** [jgraichen/redmine_dashboard#246]
I was about to report a bug saying I coudn't see the issues of a project, later realized that  it is because they are in fact attached to a sub project, yet it would be awesome that the dashboard plugin allows to list them, even maybe in different boards, one per sub-project.

**Comment by ungentilgarcon** [comment]
Or is it an issue on how I use it? please help

**Comment by jgraichen** [comment]
Hi @ungentilgarcon, on the parent projects dashboard there is an option "Include subprojects" in the right menu:

![Screenshot showing the location of the "Include subproject" option in the dashboards right menu](https://user-images.githubusercontent.com/800848/216832085-4e048036-7a15-49df-b118-1db5ebc41e21.png)

When checked, issues from subprojects will be shown too. To have one board per subproject, you will have to enter the project and open the dashboard there.
