### ISSUE TITLE
gems location

### ISSUE THREAD

**Issue by amg-web** [jgraichen/redmine_dashboard#250]
Ubuntu 20.04, ruby 2.7
project is in user space
/home/project/public_html

gem installed with:
bundle install --without development test --path vendor/bundle

Project does not look for gems in a --path vendor/bundle
only global location is supported.

`[ E 2022-06-20 14:23:33.9113 4604/Tj age/Cor/App/Implementation.cpp:221 ]: Could not spawn process for application /home/redmine/public_html: The application encountered the following error: Could not find gem 'database_cleaner-active_record (~> 2.0)' in locally installed gems.`

**Comment by jgraichen** [comment]
This plugin doesn't look in any location for gems. It  is loaded and run by the Redmine main application.

You have to follow the [Redmine Installation Guide](https://www.redmine.org/projects/redmine/wiki/redmineinstall). If you install the plugin after running `bundle install`, you will have to repeat the same call in the Redmine directory.

Besides that, user and path installs are support. They are used in the tests for this plugin, that set up a whole Redmine installation to test the plugin for each new change.
