### ISSUE TITLE
loading never ends

### ISSUE THREAD

**Issue by kmiura31** [jgraichen/redmine_dashboard#283]
When you move an issue, sometimes it is not updated while loading.

![dashboard](https://user-images.githubusercontent.com/84492716/190563688-1da3d905-7429-49df-b4c0-4a0176469e32.PNG)
![log](https://user-images.githubusercontent.com/84492716/190563710-740aa689-a13c-4580-a985-4f21b26221ee.PNG)

**Comment by kmiura31** [comment]
Redmine version is 5.0.

**Comment by jgraichen** [comment]
I am sorry, I forgot to release a patch version. Please check then new version [2.12.3](https://github.com/jgraichen/redmine_dashboard/releases/tag/v2.12.3).
