### ISSUE TITLE
Dashboard doesn't work well with multiple "closed" statuses

### ISSUE THREAD

**Issue by EdwyReed** [jgraichen/redmine_dashboard#286]
**Describe the bug**
We have two "closed" statuses: "finished" and "canceled". For some reason when I drag task into "finished", dashboard is setting status "canceled" for task.

**To Reproduce**
1. Created status "finished" and "canceled"
2. Go to Dashboard
3. Drag-n-drop task into "finished"
4. Check applied status

**Expected behavior**
Drag-n-drop into "finished" applies status "finished", into "canceled" - applies "canceled"

**Redmine**
Redmine v.5.0.2

**Comment by jgraichen** [comment]
All "closed" statuses are grouped in a "Done" column. When dragging an issue there, you will be asked for the actual status:

![Kooha-2022-11-20-21-32-27](https://user-images.githubusercontent.com/800848/202924817-a6e71b7d-e5b8-4ba1-b16d-7402eef905f0.gif)

Do you have such a dialog? Do you have any special workflow rules?

**Comment by jgraichen** [comment]
Hi @EdwyReed, did you have some time to check on the example above? The default Redmine configuration with two closed statuses works like described. How does this differ from your experience?

**Comment by hwiorn** [comment]
@jgraichen I tested redmine_dashboard 2.15.0 on redmine 5.1. But It doesn't work. There is no popup you described. I have two closed status, such as "CLOSED" and "ON HOLD". It selects the last one, "ON HOLD".

**Comment by hwiorn** [comment]
@jgraichen That was my mistake. I checked dashboard code and debug it. I confirmed the `@statuses` in the `rdb_taskboard_controller` is correct, and I found that I had misconfiguration of workflow.
