### ISSUE TITLE
Could not find gem 'rubocop (~> 1.39.0)' with platform 'x86_64-linux'

### ISSUE THREAD

**Issue by deiansp** [jgraichen/redmine_dashboard#311]
on Ubuntu 22.04, ruby 3.0.2, Rails 6.1.7, Bundler 2.3.26
`bundle install --without development test` with and without `--path vendor/bundle`
gives
`Could not find gem 'rubocop (~> 1.39.0)' with platform 'x86_64-linux'`

Can be fixed by changing in the `Gemfile`
from `gem 'rubocop', '~> 1.39.0'`
to `gem 'rubocop', require: false` (as suggested on their [website](https://rubocop.org/))

**Comment by jgraichen** [comment]
The Redmine Dashboard code is tested with a specific version because different versions have different checks. When excluding `test`, `rubocop` should not be installed at all, and it is available in the archive: https://rubygems.org/gems/rubocop/versions/1.39.0.

I am also not aware of any issues installing rubocop, neither in local development (Ubuntu 22.04), nor in [the automated tests](https://github.com/jgraichen/redmine_dashboard/actions).

Please provide full logs and terminal output, and configure bundler with persistent options too: https://bundler.io/man/bundle-config.1.html.

**Comment by mwftts** [comment]
Same issue here in QNAP docker, tried gem install rubocop, but not worked.

**Comment by jgraichen** [comment]
@mwftts Please provide actual logs, commands and output, or the Dockerfile. Otherwise, I cannot reproduce your problem.

As you can see [here](https://github.com/jgraichen/redmine_dashboard/actions), neither CI nor local development has any issues. I do need further details about your specific actions to help.

When installing `--without development test`, the `rubocop` gem shouldn't be installed at all. It is only part of the `test` group. Can you verify that the options are correctly set?

**Comment by jgraichen** [comment]
@Bonerserk Can you provide the Dockerfile and steps to reproduce the issue?

**Comment by Bonerserk** [comment]
This is the docker-compose.yaml file I used

version: '3.7'

services:
  redmine5:
    image: redmine:bullseye
    container_name: redmine5
    restart: always
  
    volumes:
      - ./volumes/redmine/data:/home/redmine/data
      - ./volumes/redmine/files:/usr/src/redmine/files
      - ./volumes/redmine/config/configuration.yml:/usr/src/redmine/config/configuration.yml
      #- ./volumes/redmine/config/environment.rb:/usr/src/redmine/config/environment.rb
      - ./volumes/redmine/config/database.yml:/usr/src/redmine/config/database.yml
      - ./volumes/redmine/plugins:/usr/src/redmine/plugins
      - ./volumes/redmine/public/themes:/usr/src/redmine/public/themes
      - ./volumes/redmine/public/favicon.ico:/usr/src/redmine/public/favicon.ico
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 3001:3000

Than I copied the plugin folder in the redmine plugin folder.
Than I execute this command in the container console: bundle install --without development test

Thanks

**Comment by web-engineer** [comment]
I had similar problem but found having installed the missing gem on the system I needed to clear the cache and remvove flags with -

```
bundle exec rake tmp:cache:clear RAILS_ENV=production
bundle config --delete without
bundle config --delete with
bundle install
```

**Comment by drjeon92** [comment]
![Uploading image.png…]()

**Comment by drjeon92** [comment]
root@1b135de67f02:/usr/src/redmine# bundle exec rake tmp:cache:clear RAILS_ENV=production
Could not find gem 'rspec-rails' in locally installed gems.
Run `bundle install` to install missing gems.
root@1b135de67f02:/usr/src/redmine# gem install rspec-rails
Fetching rspec-rails-6.0.1.gem
Successfully installed rspec-rails-6.0.1
1 gem installed
root@1b135de67f02:/usr/src/redmine# bundle exec rake tmp:cache:clear RAILS_ENV=production
Could not find gem 'capybara (~> 3.38.0)' in locally installed gems.
Run `bundle install` to install missing gems.
root@1b135de67f02:/usr/src/redmine# gem install capybara
Fetching regexp_parser-2.6.2.gem
Fetching xpath-3.2.0.gem
Fetching capybara-3.38.0.gem
Fetching rack-3.0.4.1.gem
Successfully installed xpath-3.2.0
Successfully installed regexp_parser-2.6.2
Successfully installed rack-3.0.4.1
Successfully installed capybara-3.38.0
4 gems installed
root@1b135de67f02:/usr/src/redmine# bundle exec rake tmp:cache:clear RAILS_ENV=production
Could not find gem 'rubocop (~> 1.44.0)' in locally installed gems.
Run `bundle install` to install missing gems.
root@1b135de67f02:/usr/src/redmine# gem install rubocop
Fetching parser-3.2.0.0.gem
Fetching ruby-progressbar-1.11.0.gem
Fetching unicode-display_width-2.4.2.gem
Fetching rainbow-3.1.1.gem
Fetching ast-2.4.2.gem
Fetching rubocop-ast-1.24.1.gem
Fetching rubocop-1.44.1.gem
Fetching parallel-1.22.1.gem
Successfully installed unicode-display_width-2.4.2
Successfully installed ruby-progressbar-1.11.0
Successfully installed ast-2.4.2
Successfully installed parser-3.2.0.0
Successfully installed rubocop-ast-1.24.1
Successfully installed rainbow-3.1.1
Successfully installed parallel-1.22.1
Successfully installed rubocop-1.44.1
8 gems installed
root@1b135de67f02:/usr/src/redmine# bundle exec rake tmp:cache:clear RAILS_ENV=production
Could not find gem 'rubocop (~> 1.44.0)' with platform 'x86_64-linux' in locally installed gems.

The source contains the following gems matching 'rubocop (~> 1.44.0)':
  * rubocop-1.44.1
Run `bundle install` to install missing gems.
root@1b135de67f02:/usr/src/redmine# 


cant resolve this problem

**Comment by jgraichen** [comment]
I've confirmed that the plugin is working, is working with current Redmine, and current Ruby. 

The docker image mentioned above is built at https://github.com/docker-library/redmine and does not have a documented way for installing plugins. They explicitly mangle with the installation paths, customize and replace files and configurations in their image.

Several issues there report problems with installing (different) plugins in their recent image. Please ask them for advice on how to install plugins in their image. The docker image is not the expected way for installing Redmine. All common guides on installing plugins will _not_ just work inside the docker image. As far as I saw in their Dockerfiles, you will have to at least use the correct user, or use `guso` and other helpers to install the plugins and run e.g. `bundle install` as the correct user and in the correct environment.

Unfortunately, I cannot provide assistance for every appliance or docker image out there, on how to correctly install plugins, and keep these guides up-to-date whenever they change or update their image. Please ask https://github.com/docker-library/redmine on how to correctly install plugins.

The plugin itself is tested for all current Redmine and Ruby versions automatically, each test setting up and configuring a regular full Redmine installation before running tests, e.g. see [here](https://github.com/jgraichen/redmine_dashboard/actions/runs/4073411882/jobs/7017312368). This is as much as I can provide. I am sorry I have no quick solution for you.

**Comment by jgraichen** [comment]
Please try again with v2.12.4. It might have improved working in broker docker container environments. Please, please also ask the docker image maintainers, why they have issues with installing plugins.

**Comment by drjeon92** [comment]
Thank you for always.
