### ISSUE TITLE
Dashboard is not refreshed 

### ISSUE THREAD

**Issue by marmat1** [jgraichen/redmine_dashboard#314]
**Describe the bug**
After moving a card between columns, the view is not updated, and "loading" message doesn´t dissapear. Probably same issue as https://github.com/jgraichen/redmine_dashboard/issues/283

![image](https://user-images.githubusercontent.com/101202803/203942478-56b459d3-f86e-45d4-96ba-cb907e81dc54.png)

**To Reproduce**
Move any card between colums

**Screenshots**
![image](https://user-images.githubusercontent.com/101202803/203942478-56b459d3-f86e-45d4-96ba-cb907e81dc54.png)

![image](https://user-images.githubusercontent.com/101202803/203943220-ef97eec8-8f96-4311-89de-db4f8c2fd11d.png)

**Redmine**

```
Environment:
  Redmine version                5.0.2.stable
  Ruby version                   2.7.4-p191 (2021-07-07) [x86_64-linux]
  Rails version                  6.1.6
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                sendmail
Redmine settings:
  Redmine theme                  Televes
SCM:
  Subversion                     1.10.2
  Git                            2.27.0
  Filesystem                     
Redmine plugins:
  redmine_dashboard              2.12.3
```

**Comment by marmat1** [comment]
Log info:
I, [2022-11-25T10:05:44.414887 #3923327]  INFO -- : [a8d96acb-c9ce-470a-9add-7828c4e7950e]   Rendered plugins/redmine_dashboard/app/views/rdb_dashboard/error.js.erb (Duration: 1.0ms | Allocations: 210)
I, [2022-11-25T10:05:44.457077 #3923327]  INFO -- : [a8d96acb-c9ce-470a-9add-7828c4e7950e] Completed 200 OK in 190ms (Views: 87.3ms | ActiveRecord: 29.9ms | Allocations: 53018)
I, [2022-11-25T10:05:46.998282 #3923327]  INFO -- : [c3815713-ab4b-4919-a62f-35a4218cc7b4] Started GET "/projects/test-3/rdb/taskboard/move?issue=10572&lock_version=2&column=s1&group=all&_=1669367141648" for 192.168.178.216 at 2022-11-25 10:05:46 +0100
I, [2022-11-25T10:05:47.000418 #3923327]  INFO -- : [c3815713-ab4b-4919-a62f-35a4218cc7b4] Processing by RdbTaskboardController#move as JS
I, [2022-11-25T10:05:47.000516 #3923327]  INFO -- : [c3815713-ab4b-4919-a62f-35a4218cc7b4]   Parameters: {"issue"=>"10572", "lock_version"=>"2", "column"=>"s1", "group"=>"all", "_"=>"1669367141648", "id"=>"test-3"}
I, [2022-11-25T10:05:47.009224 #3923327]  INFO -- : [c3815713-ab4b-4919-a62f-35a4218cc7b4]   Current user: xxxxx (id=13)
I, [2022-11-25T10:05:47.083268 #3923327]  INFO -- : [c3815713-ab4b-4919-a62f-35a4218cc7b4] = Running shared code for Issue (#10572) "Task #10572: Test"
I, [2022-11-25T10:05:47.084773 #3923327]  INFO -- : [c3815713-ab4b-4919-a62f-35a4218cc7b4] = Finished running shared code for Issue (#10572) "Task #10572: Test"
I, [2022-11-25T10:05:47.086172 #3923327]  INFO -- : [c3815713-ab4b-4919-a62f-35a4218cc7b4] = Running before_save custom workflows for Issue (#10572) "Task #10572: Test"
I, [2022-11-25T10:05:47.087374 #3923327]  INFO -- : [c3815713-ab4b-4919-a62f-35a4218cc7b4] == Running before_save custom workflow "[Incidence] Closed date"
I, [2022-11-25T10:05:47.087540 #3923327]  INFO -- : [c3815713-ab4b-4919-a62f-35a4218cc7b4] == Running before_save custom workflow "api_add_issue_no_notifications"
E, [2022-11-25T10:05:47.088746 #3923327] ERROR -- : [c3815713-ab4b-4919-a62f-35a4218cc7b4] xxxx, en el wf de area_list_project_issues_wf nil 
I, [2022-11-25T10:05:47.088821 #3923327]  INFO -- : [c3815713-ab4b-4919-a62f-35a4218cc7b4] = Finished running before_save custom workflows for Issue (#10572) "Task #10572: Test"
I, [2022-11-25T10:05:47.101755 #3923327]  INFO -- : [c3815713-ab4b-4919-a62f-35a4218cc7b4] = Running after_save custom workflows for Issue (#10572) "Task #10572: Test"
I, [2022-11-25T10:05:47.103413 #3923327]  INFO -- : [c3815713-ab4b-4919-a62f-35a4218cc7b4] = Finished running after_save custom workflows for Issue (#10572) "Task #10572: Test"
I, [2022-11-25T10:05:47.109339 #3923327]  INFO -- : [c3815713-ab4b-4919-a62f-35a4218cc7b4] [ActiveJob] Enqueued AdditionalTagsRemoveUnusedTagJob (Job ID: 953c3879-4359-433c-9b0b-9c1786250dcd) to Async(additional_tags)
I, [2022-11-25T10:05:47.111674 #3923327]  INFO -- : [c3815713-ab4b-4919-a62f-35a4218cc7b4] Completed 500 Internal Server Error in 111ms (ActiveRecord: 48.4ms | Allocations: 23614)
I, [2022-11-25T10:05:47.110208 #3923327]  INFO -- : [ActiveJob] [AdditionalTagsRemoveUnusedTagJob] [953c3879-4359-433c-9b0b-9c1786250dcd] Performing AdditionalTagsRemoveUnusedTagJob (Job ID: 953c3879-4359-433c-9b0b-9c1786250dcd) from Async(additional_tags) enqueued at 2022-11-25T09:05:47Z
F, [2022-11-25T10:05:47.112353 #3923327] FATAL -- : [c3815713-ab4b-4919-a62f-35a4218cc7b4]   
[c3815713-ab4b-4919-a62f-35a4218cc7b4] NoMethodError (undefined method `map' for nil:NilClass):
[c3815713-ab4b-4919-a62f-35a4218cc7b4]   
[c3815713-ab4b-4919-a62f-35a4218cc7b4] plugins/redmine_checklists/app/models/journal_checklist_history.rb:131:in `force_object'
[c3815713-ab4b-4919-a62f-35a4218cc7b4] plugins/redmine_checklists/app/models/journal_checklist_history.rb:44:in `initialize'
[c3815713-ab4b-4919-a62f-35a4218cc7b4] plugins/redmine_checklists/lib/redmine_checklists/hooks/controller_issues_hook.rb:9:in `new'
[c3815713-ab4b-4919-a62f-35a4218cc7b4] plugins/redmine_checklists/lib/redmine_checklists/hooks/controller_issues_hook.rb:9:in `controller_issues_edit_after_save'
[c3815713-ab4b-4919-a62f-35a4218cc7b4] lib/redmine/hook.rb:66:in `block (2 levels) in call_hook'
[c3815713-ab4b-4919-a62f-35a4218cc7b4] lib/redmine/hook.rb:66:in `each'
[c3815713-ab4b-4919-a62f-35a4218cc7b4] lib/redmine/hook.rb:66:in `block in call_hook'
[c3815713-ab4b-4919-a62f-35a4218cc7b4] lib/redmine/hook.rb:63:in `tap'
[c3815713-ab4b-4919-a62f-35a4218cc7b4] lib/redmine/hook.rb:63:in `call_hook'
[c3815713-ab4b-4919-a62f-35a4218cc7b4] lib/redmine/hook.rb:96:in `call_hook'
[c3815713-ab4b-4919-a62f-35a4218cc7b4] plugins/redmine_dashboard/app/controllers/rdb_taskboard_controller.rb:57:in `update'
[c3815713-ab4b-4919-a62f-35a4218cc7b4] plugins/redmine_dashboard/app/controllers/rdb_taskboard_controller.rb:25:in `move'
[c3815713-ab4b-4919-a62f-35a4218cc7b4] lib/redmine/sudo_mode.rb:61:in `sudo_mode'

**Comment by jgraichen** [comment]
The error mentioned in the log happens inside the `redmine_checklists` plugin, that is not open source. Therefore, I cannot check the source. Please ask them for support.

I'll check if I can find anything regarding the error above, `rdbDADShowIssue is not a function`.

**Comment by marmat1** [comment]
I have uninstalled checklist plugin and now the dashboard is working again. I'll report checklist plugin developers. Thanks.
