### ISSUE TITLE
Plugin installation cause "Thin Redmine" and "Thin redmine 2" stop

### ISSUE THREAD

**Issue by yaya33130** [jgraichen/redmine_dashboard#322]
Hi, 

I'm using Bitnami redmine  package

When I try to install this plugin, the servers "Thin redmine" and "Thin redmine2" stop, and redmine don't start..

Any idea  please ?

**Comment by jgraichen** [comment]
Please provide some details about what you did. This should include commands, their output, the log files created, a screencast, or screenshots of the steps you did.
