### ISSUE TITLE
Installation over bitnami/redmine

### ISSUE THREAD

**Issue by emilianobaum** [jgraichen/redmine_dashboard#334]
Hi, I can't install redmine_dashboard over _bitnami/redmine_ using the image:

* bitnami/redmine:5.0.4-debian-11-r9

To install, I go into the container (using docker exec), do an update, and install some packages:

* ruby-dev
* build-essential
*zlib1g-dev

I then clone the  plugin redmine_dashboard into /bitnami/redmine/plugins and make the _bundle install_:

> root@59e6ca4c92e3:/bitnami/redmine/plugins/redmine_dashboard# bundle install
> Don't run Bundler as root. Bundler can ask for sudo if it is needed, and installing your bundle as root will break this application for all non-root users on this machine.
> Fetching gem metadata from https://rubygems.org/...........
> Resolving dependencies.......
> Fetching rake 13.0.6
> Installing rake 13.0.6
> Fetching minitest 5.17.0
> Fetching builder 3.2.4
> Fetching erubi 1.12.0
> Fetching rack 2.2.5
> Fetching concurrent-ruby 1.1.10
> Fetching racc 1.6.2
> Fetching public_suffix 5.0.1
> Fetching ast 2.4.2
> Using bundler 2.3.26
> Fetching regexp_parser 2.6.1
> Fetching matrix 0.4.2
> Fetching mini_mime 1.1.2
> Fetching crass 1.0.6
> Installing builder 3.2.4
> Installing crass 1.0.6
> Installing mini_mime 1.1.2
> Installing racc 1.6.2 with native extensions
> Installing minitest 5.17.0
> Installing erubi 1.12.0
> Installing ast 2.4.2
> Fetching database_cleaner-core 2.0.1
> Installing rack 2.2.5
> Installing matrix 0.4.2
> Installing regexp_parser 2.6.1
> Fetching diff-lcs 1.5.0
> Installing public_suffix 5.0.1
> Fetching json 2.6.3
> Fetching method_source 1.0.0
> Fetching parallel 1.22.1
> Installing database_cleaner-core 2.0.1
> Installing parallel 1.22.1
> Installing method_source 1.0.0
> Installing diff-lcs 1.5.0
> Fetching thor 1.2.1
> Installing json 2.6.3 with native extensions
> Fetching zeitwerk 2.6.6
> Installing concurrent-ruby 1.1.10
> Fetching rainbow 3.1.1
> Using rexml 3.2.5
> Fetching rspec-support 3.12.0
> Fetching ruby-progressbar 1.11.0
> Installing rainbow 3.1.1
> Installing thor 1.2.1
> Installing zeitwerk 2.6.6
> Fetching unicode-display_width 2.4.2
> Fetching temple 0.8.2
> Installing ruby-progressbar 1.11.0
> Installing rspec-support 3.12.0
> Installing unicode-display_width 2.4.2
> Fetching tilt 2.0.11
> Installing temple 0.8.2
> Fetching addressable 2.8.1
> Fetching parser 3.2.0.0
> Installing tilt 2.0.11
> Fetching rack-test 2.0.2
> Fetching nokogiri 1.13.10 (x86_64-linux)
> Fetching rspec-core 3.12.0
> Fetching rspec-expectations 3.12.2
> Fetching rspec-mocks 3.12.2
> Installing addressable 2.8.1
> Installing rack-test 2.0.2
> Fetching slim 4.1.0
> Installing rspec-mocks 3.12.2
> Installing rspec-expectations 3.12.2
> Installing rspec-core 3.12.0
> Fetching tzinfo 2.0.5
> Fetching i18n 1.12.0
> Installing parser 3.2.0.0
> Fetching rspec 3.12.0
> Installing tzinfo 2.0.5
> Installing i18n 1.12.0
> Installing rspec 3.12.0
> Fetching rubocop-ast 1.24.1
> Fetching activesupport 7.0.4
> Installing rubocop-ast 1.24.1
> Installing activesupport 7.0.4
> Fetching activemodel 7.0.4
> Fetching rubocop 1.42.0
> Installing activemodel 7.0.4
> Fetching activerecord 7.0.4
> Installing nokogiri 1.13.10 (x86_64-linux)
> Installing slim 4.1.0
> Installing rubocop 1.42.0
> Installing activerecord 7.0.4
> Fetching database_cleaner-active_record 2.0.1
> Fetching xpath 3.2.0
> Fetching rails-dom-testing 2.0.3
> Fetching loofah 2.19.1
> Installing database_cleaner-active_record 2.0.1
> Installing rails-dom-testing 2.0.3
> Installing xpath 3.2.0
> Installing loofah 2.19.1
> Fetching capybara 3.38.0
> Fetching rails-html-sanitizer 1.4.4
> Fetching slim_lint 0.22.1
> Installing rails-html-sanitizer 1.4.4
> Fetching actionview 7.0.4
> Installing slim_lint 0.22.1
> Installing capybara 3.38.0
> Installing actionview 7.0.4
> Fetching actionpack 7.0.4
> Installing actionpack 7.0.4
> Fetching railties 7.0.4
> Installing railties 7.0.4
> Fetching slim-rails 3.5.1
> Fetching rspec-rails 6.0.1
> Installing slim-rails 3.5.1
> Installing rspec-rails 6.0.1
> Bundle complete! 8 Gemfile dependencies, 56 gems now installed.
> Use `bundle info [gemname]` to see where a bundled gem is installed.

The process ends without a problem, but when I restart the container I get an _Exit 1 _ code:

> redmine_1  | redmine 13:03:36.63
> redmine_1  | redmine 13:03:36.63 Welcome to the Bitnami redmine container
> redmine_1  | redmine 13:03:36.63 Subscribe to project updates by watching https://github.com/bitnami/containers
> redmine_1  | redmine 13:03:36.64 Submit issues and feature requests at https://github.com/bitnami/containers/issues
> redmine_1  | redmine 13:03:36.64
> redmine_1  | redmine 13:03:36.64 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
> redmine_1  | redmine 13:03:36.65 INFO  ==> Validating settings in POSTGRESQL_CLIENT_* env vars
> redmine_1  | redmine 13:03:36.67 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
> redmine_1  | redmine 13:03:36.68 INFO  ==> Restoring persisted Redmine installation
> redmine_1  | redmine 13:03:36.71 INFO  ==> Trying to connect to the database server
> redmine_1  | redmine 13:03:36.86 INFO  ==> Executing database migrations
> docker-compose_redmine_1 exited with code 1

At the end of the update and installation of packages I performed a restart of the container, to rule out a failure associated with that.

Any suggestions?

Regards, Emiliano

**Comment by jgraichen** [comment]
Please ask `bitnami/redmine` on how to correctly install plugins in their image. The log does not show anything that indicates an issue with this plugin.

You will mostly like to have to use other commands to install a plugin in the image, use a specific user, a specific directory, environment, wrapper or utility tool. Docker images are _not_ regular Linux system, the default plugin installation guides _DO NOT_ apply. Please ask the appliance vendor for assistance.

Unfortunately, I cannot support any appliance and docker image out there. I do not have the time to research how they built their specific image, how they differ from a regular installation, what will be needed to install a plugin correctly there, and keep all of that up-to-date whenever they update or change their image. Please ask bitname/redmine on how to correctly install plugins.

The plugin itself is tested for all current Redmine and Ruby versions automatically, each test setting up and configuring a regular full Redmine installation before running tests, e.g. see [here](https://github.com/jgraichen/redmine_dashboard/actions/runs/4073411882/jobs/7017312368). This is as much as I can provide. I am sorry I have no quick solution for you.

**Comment by emilianobaum** [comment]
Hi @jgraichen, the problem is when the redmine pod restarts and tries to recreate/install the tables, it doesn't correctly handle the exception when the table is already created. This happens with all plugins that use the database.
I did a pluginless release using plugins that create tables in the redmine database, and I'm already tuning the redmine docker image for k8s by installing the necessary dependencies, so I think I need to do an automatic deletion of tables for the dashboard linked table and other plugins like the ones from AlphaNodes.
May be this info is usseles for someone trying to install in k8s...
Thanks for your reply!

**Comment by jgraichen** [comment]
@emilianobaum Rails migrations do track what migrations have been run in the `schema_migrations` table. Running migrations twice shall not result in an error unless much more is broken (e.g. data loss)

Also, please note that this plugin's current release v2 does not create/uses any tables. If you are creating tables for this plugin, you might be installing the dev branch.

**Comment by emilianobaum** [comment]
Yes @jgraichen, I follow the guide and delete the plugin folder, but one or more tables persist and is the cause of the error.
When you do this step `bundle install --without development test`, the installation fails
I'm working on another project at the moment, but in the next few weeks I'll pick up on this one and if I found the solution by removing the old tables, I'll paste it here. Like other installation issues on k8s and simulated failover and failback scenarios, I think one possibility is to add to the run.sh file with a call to a .sh script that removes the problematic tables, but I haven't tried that so far.
