### ISSUE TITLE
Fresh install on Redmine 5.0.4 - plugin_assets fail to load

### ISSUE THREAD

**Issue by web-engineer** [jgraichen/redmine_dashboard#337]
**Describe the bug**
Installed on a 5.0.4 redmine install with ruby 3.1.3 and all appears to be installed fine, however the dashboard appears as unstyled text -

<img width="263" alt="Screenshot 2023-01-20 at 12 40 46" src="https://user-images.githubusercontent.com/230107/213698149-57c3eb35-3922-49af-a776-a9542cf4e7c6.png">

Looking at network panel we can see none of the CSS/JS has loaded.

I did notice that I had to add the hostname into the *config/environments/development.rb*  (running in development)

```
# frozen_string_literal: true

require 'active_support/core_ext/integer/time'

Rails.application.configure do
  # Settings specified here will take precedence over those in config/application.rb.
  config.hosts << "DOMAIN" 
```
Is this a 3.1.3 ruby problem? Has something changed with the routing perhaps... my ruby knowlege is very sparse...

**To Reproduce**

1. Install on 5.0.4
2. Add a dashboard to a project
3. Navigate to dashboard

**Expected behavior**

For the javascripts/css to load.

**Screenshots**

<img width="263" alt="Screenshot 2023-01-20 at 12 40 46" src="https://user-images.githubusercontent.com/230107/213697604-672cf876-ca18-483e-b400-1eefd8e446c8.png">

<img width="418" alt="Screenshot 2023-01-20 at 12 43 16" src="https://user-images.githubusercontent.com/230107/213697670-5f382011-1d28-4752-9808-febea6e52096.png">

**Redmine**

```
Environment:
  Redmine version                5.0.4.stable
  Ruby version                   3.1.3-p185 (2022-11-24) [x86_64-linux]
  Rails version                  6.1.7
  Environment                    development
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
Redmine settings:
  Redmine theme                  We-circle (includes JavaScript)
SCM:
  Subversion                     1.7.14
  Git                            1.8.3.1
  Filesystem                     
Redmine plugins:
  additional_tags                1.0.8
  additionals                    3.0.9-main
  redmine_dashboard              2.12.3
```

Add details about your server:

- OS: Centos 7
- Appliance: Bare metal

**Additional context**

If we visit any of the routes that are failign we get the following from rails -

No route matches [GET] "/plugin_assets/redmine_dashboard_linked/stylesheets/dashboard.css"

<img width="1111" alt="Screenshot 2023-01-20 at 12 46 25" src="https://user-images.githubusercontent.com/230107/213698524-d5581c91-d0b2-4369-bfcc-1e937e61920c.png">

Yet from terminal we can see these files exist -

<img width="1106" alt="Screenshot 2023-01-20 at 12 48 31" src="https://user-images.githubusercontent.com/230107/213698613-01eac28b-1607-47e2-8cc4-6b525a23edaa.png">

**Comment by jgraichen** [comment]
You seem to run the server in development mode (e.g. no `RAILS_ENV=production`). Any server should run in production mode. Please add `RAILS_ENV=production`.

Background: The plugin tries to load assets from `redmine_dashboard_linked/` which is a symlinked folder in the development setup and not available on a production system. Redmine does copy all assets into its public directory on boot, but for development this means I would have to restart Redmine for every change. Please use `RAILS_ENV=production` when running a server.

**Comment by web-engineer** [comment]
Ahh - thought it might be something simple, were running in dev as were debugging upgrading an exisiting isntallation and getting everythign working.

Just realised my paths shown in the terminal confirm what your saying - missed the _linked

As a quick fix I just symlinked redmine_dashboard_linked to redmine_dashboard in situ -

```
drwxr-xr-x. 4 webengineer psacln  44 Jan 20 12:28 redmine_dashboard
lrwxrwxrwx. 1 webengineer psacln  19 Jan 20 14:42 redmine_dashboard_linked -> ./redmine_dashboard
```
Now this runs fine for me in dev mode - explains now why I had some fun with gems too having to add some dev packages to the system... Will be in production soon - thanks for your help!

**Comment by jgraichen** [comment]
Great that it did work. 

Please note that unless you are developing on the Redmine code or any plugin itself, you should always run with `RAILS_ENV=production`. Even if the server is for testing or staging purposes. The `RAILS_ENV` substantially influences how the Redmine application itself runs, e.g. disabling caches, reloading code on every request, taking different configuration options, etc. This will hide potential issues for "production" and greatly affect performance (testing).

**Comment by web-engineer** [comment]
Thanks for the advice - we only ended up in dev as we were haivng trouble getting things started - ruby was too old on this setup as was the C compliler, so we've been on a journey of compilation, building ruby and discovering rbenv, managing gems and a few other fun things... now things are less broken I'll get the install switched over to production!

Thanks again for your advice and help - much apreciatted - we do have some large projects on our redmine so will put your plugin through its paces soon ;)
