### ISSUE TITLE
Error with using with docker

### ISSUE THREAD

**Issue by qawsed55** [jgraichen/redmine_dashboard#349]
1. I'm run official Redmine docker container (5.0.4)
2. Attach volumes Plugins and put Redmine_Dashboard's files there
3. Start container and see this error massage:

```
Fetching gem metadata from https://rubygems.org/.........
Could not find gem 'rubocop (~> 1.45.0)' with platform 'x86_64-linux' in
rubygems repository https://rubygems.org/ or installed locally.
The source contains the following gems matching 'rubocop (~> 1.45.0)':
  * rubocop-1.45.0
  * rubocop-1.45.1
```

And container fails.
Also tried to add files to container and run 
bundle install --without development test

But, there are message about do not using --without and somethig else (window was closed, sorry)
And also it write error about two gems of rubocop.

Please, help to run plugin. Thanks.

**Comment by qawsed55** [comment]
v2.12.3 - working as described
v3 (development) - working as described
v2.12.2 - works fine.

**Comment by jgraichen** [comment]
Please try 2.12.4 and see https://github.com/jgraichen/redmine_dashboard/issues/311#issuecomment-1418060431 as well.

> The docker image mentioned above is built at https://github.com/docker-library/redmine and does not have a documented way for installing plugins. They explicitly mangle with the installation paths, customize and replace files and configurations in their image.
> 
> Several issues there report problems with installing (different) plugins in their recent image. Please ask them for advice on how to install plugins in their image. The docker image is not the expected way for installing Redmine. All common guides on installing plugins will not just work inside the docker image. As far as I saw in their Dockerfiles, you will have to at least use the correct user, or use guso and other helpers to install the plugins and run e.g. bundle install as the correct user and in the correct environment.
> 
> Unfortunately, I cannot provide assistance for every appliance or docker image out there, on how to correctly install plugins, and keep these guides up-to-date whenever they change or update their image. Please ask https://github.com/docker-library/redmine on how to correctly install plugins.
