### ISSUE TITLE
Cannot update issue's status from the Dashboard page

### ISSUE THREAD

**Issue by victor-vc** [jgraichen/redmine_dashboard#369]
Although the user with the role below is able to change the status of his own issues either from the Issues page (by right click) or by editing the issue itself, dragging the issue from one column to another doesn't work (neither `New` to `In progress` nor `In progress` to `Done`). It seems to be working but when I release the issue to the target column the loading animation pop-up shows up and won't disappear until I refresh the page. The issue's status wasn't updated, and it wasn't moved to the target column.

Permissions
![image](https://user-images.githubusercontent.com/67239636/226191544-8721c490-192a-4b37-8b3e-24d4c4876757.png)

Workflow
![image](https://user-images.githubusercontent.com/67239636/226192224-d2a38480-c70b-4f01-a373-bc3ed0bfb579.png)

**Comment by jgraichen** [comment]
Please follow the bug report template.

At least provide server log, and client and server details. If you are testing with the `redmine_checklists` plugin, please see #364.

**Comment by victor-vc** [comment]
Clients Chrome 111.0.5563.65 and Firefox 111.0

```
Environment:
  Redmine version                5.0.5.stable
  Ruby version                   3.0.5-p211 (2022-11-24) [x86_64-linux]
  Rails version                  6.1.7.2
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
Redmine settings:
  Redmine theme                  Alternate
SCM:
  Git                            2.39.2
  Filesystem                     
Redmine plugins:
  mega_calendar                  1.9.3
  redmine_dashboard              2.12.4
```
```
I, [2023-03-19T20:06:08.270336 #145461]  INFO -- : [2963df5a-fc0a-43ff-a141-722371a99837] Started GET "/projects/products-posting/rdb/taskboard/move?issue=81&lock_version=1&column=s13&group=tracker-8&_=1679249156897" for 81.196.3.43 at 2023-03-19 20:06:08 +0200
I, [2023-03-19T20:06:08.271587 #145461]  INFO -- : [2963df5a-fc0a-43ff-a141-722371a99837] Processing by RdbTaskboardController#move as JS
I, [2023-03-19T20:06:08.271714 #145461]  INFO -- : [2963df5a-fc0a-43ff-a141-722371a99837]   Parameters: {"issue"=>"81", "lock_version"=>"1", "column"=>"s13", "group"=>"tracker-8", "_"=>"1679249156897", "id"=>"products-posting"}
I, [2023-03-19T20:06:08.277104 #145461]  INFO -- : [2963df5a-fc0a-43ff-a141-722371a99837]   Current user: victor (id=5)
I, [2023-03-19T20:06:08.303482 #145461]  INFO -- : [2963df5a-fc0a-43ff-a141-722371a99837]   Rendered common/error.html.erb (Duration: 0.8ms | Allocations: 234)
I, [2023-03-19T20:06:08.303800 #145461]  INFO -- : [2963df5a-fc0a-43ff-a141-722371a99837] Completed 403 Forbidden in 32ms (Views: 7.0ms | ActiveRecord: 7.5ms | Allocations: 6541)
```

**Comment by victor-vc** [comment]
It's worth mentioning that enabling `Edit issues` in user's Role "fixes" the issues. However, the user should be able to update the status of its own issues by dragging & dropping them even without  `Edit issues` checked.

**Comment by jgraichen** [comment]
If that is your issue, please see #363.

**Comment by victor-vc** [comment]
The version v2.13.0 fixed the issue. Thanks for the quick fix. Apart from that, the Dashboard plug-in is a great addition to Redmine.
