### ISSUE TITLE
Save dashboard view after configuring

### ISSUE THREAD

**Issue by ppoektos** [jgraichen/redmine_dashboard#39]
Suppose user configured dashboard view for himself.
After user logout and login again he lost view configuration.
And he need again to setup dashboard.
Need some kind of "save settings". And then "load my view".

**Comment by drmistral** [comment]
+1 - It would be definitely useful to persist the dashboard configuration at db level (set per user or per project) or, alternatively, at least at browser level (in the HTML5 Web Database).  
Any possibility to provide that small improvement meanwhile working in next major version?

**Comment by jgraichen** [comment]
The dashboard view settings are now stored in the user preferences in the database. They will be persistent, shared between browsers but unique per user.
