### ISSUE TITLE
Empty Dashboard on fresh install

### ISSUE THREAD

**Issue by Doctor-Who** [jgraichen/redmine_dashboard#453]
**Describe the bug**
When trying access to dashboard, everything is empty, see screenshot below : 
![Capture d’écran du 2023-12-14 09-47-06](https://github.com/jgraichen/redmine_dashboard/assets/5890416/7eced139-c1ba-49f8-a7f7-6aa7d6f2d51d)

**To Reproduce*

I've follow the configuration part.
Activate dashboard on all project
And go to users and roles and try to check all type to see if it fix the problem but still nothing.

**Expected behavior**
Supposed to see card relative to ticket I've create or assigned to me ?? 

**Redmine**

```
Environment:
  Redmine version                5.0.4.stable
  Ruby version                   3.1.2-p20 (2022-04-12) [x86_64-linux-gnu]
  Rails version                  6.1.7.3
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
Redmine settings:
  Redmine theme                  Default
SCM:
  Filesystem                     
Redmine plugins:
  redmine_dashboard              2.15.0
```

Add details about your server:

OS Debian 12, 
install Redmine and Passenger from Debian official repository.

**Client information**
Add details about your browser and system here. This is important to debug client problems.

- Tested on Firefox 120.01 on Linux Pop!_OS
- Tested on Brave v1.61.101 / Chromium  120.0.6099.7

**Comment by jgraichen** [comment]
There appears to be no JavaScript and stylesheets loaded. Did you run all the installation steps for plugins?

Assets from plugins are copied to the `public/` directory when Redmine boots. Can you please check your Redmine logs if it did that, or if there were any issues (e.g. permissions problems).

Also, with packaged Redmine installations, there might be extra or different steps, depending on the package.

**Comment by jgraichen** [comment]
You can also check your browser console for errors and if requests for the assets fail. The screenshot looks exactly like the page would look without the required assets.

**Comment by Doctor-Who** [comment]
Finally found it! There was an issue with the declaration of the directory in the vhost. 
It's now resolved, and we're going to use this amazing plugin. Many thanks for your help!
