### ISSUE TITLE
I installed the dashboard, but the dashboard showed nothing

### ISSUE THREAD

**Issue by yourlin** [jgraichen/redmine_dashboard#80]
Redmine 2.6 
redmine_dashboard 2.4

I installed the dashboard, but the dashboard showed nothing
The dashboard page went blank.

Any ideas?

**Comment by jgraichen** [comment]
Can you please provide the redmine log?

**Comment by yourlin** [comment]
Connecting to database specified by database.yml
Creating scope :sorted. Overwriting existing method User.sorted.
Creating scope :sorted. Overwriting existing method Group.sorted.
Creating scope :system. Overwriting existing method Enumeration.system.
Started GET "/rdb/dashboards" for 192.168.233.1 at 2015-01-08 07:29:38 +0800
Processing by RdbController#index as HTML
  Current user: yourlin (id=5)
  Rendered plugins/redmine_dashboard/app/views/rdb/index.html.slim within layouts/base (18.8ms)
  Rendered plugins/redmine_code_review/app/views/code_review/_html_header.html.erb (0.7ms)
  Rendered plugins/clipboard_image_paste/app/views/clipboard_image_paste/_headers.html.erb (1.8ms)
  Rendered plugins/redmine_banner/app/views/banner/_project_body_bottom.html.erb (0.7ms)
  Rendered plugins/redmine_code_review/app/views/code_review/_body_bottom.html.erb (1.1ms)
  Rendered plugins/clipboard_image_paste/app/views/clipboard_image_paste/_add_form.html.erb (33.0ms)
Completed 200 OK in 524.0ms (Views: 359.5ms | ActiveRecord: 17.3ms)
Started GET "/plugin_assets/redmine_dashboard/main.min.css" for 192.168.233.1 at 2015-01-08 07:29:39 +0800

ActionController::RoutingError (No route matches [GET] "/plugin_assets/redmine_dashboard/main.min.css"):
  actionpack (3.2.21) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
  railties (3.2.21) lib/rails/rack/logger.rb:32:in `call_app'
  railties (3.2.21) lib/rails/rack/logger.rb:16:in `block in call'
  activesupport (3.2.21) lib/active_support/tagged_logging.rb:22:in `tagged'
  railties (3.2.21) lib/rails/rack/logger.rb:16:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/request_id.rb:22:in `call'
  rack (1.4.5) lib/rack/methodoverride.rb:21:in `call'
  rack (1.4.5) lib/rack/runtime.rb:17:in `call'
  activesupport (3.2.21) lib/active_support/cache/strategy/local_cache.rb:72:in `call'
  rack (1.4.5) lib/rack/lock.rb:15:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/static.rb:83:in `call'
  rack-cache (1.2) lib/rack/cache/context.rb:136:in `forward'
  rack-cache (1.2) lib/rack/cache/context.rb:245:in `fetch'
  rack-cache (1.2) lib/rack/cache/context.rb:185:in `lookup'
  rack-cache (1.2) lib/rack/cache/context.rb:66:in `call!'
  rack-cache (1.2) lib/rack/cache/context.rb:51:in `call'
  railties (3.2.21) lib/rails/engine.rb:484:in `call'
  railties (3.2.21) lib/rails/application.rb:231:in `call'
  rack (1.4.5) lib/rack/content_length.rb:14:in `call'
  rack (1.4.5) lib/rack/handler/webrick.rb:59:in `service'
  /usr/share/ruby/webrick/httpserver.rb:138:in `service'
  /usr/share/ruby/webrick/httpserver.rb:94:in `run'
  /usr/share/ruby/webrick/server.rb:295:in `block in start_thread'


Started GET "/plugin_assets/redmine_dashboard/main.min.js" for 192.168.233.1 at 2015-01-08 07:29:39 +0800

ActionController::RoutingError (No route matches [GET] "/plugin_assets/redmine_dashboard/main.min.js"):
  actionpack (3.2.21) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
  railties (3.2.21) lib/rails/rack/logger.rb:32:in `call_app'
  railties (3.2.21) lib/rails/rack/logger.rb:16:in `block in call'
  activesupport (3.2.21) lib/active_support/tagged_logging.rb:22:in `tagged'
  railties (3.2.21) lib/rails/rack/logger.rb:16:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/request_id.rb:22:in `call'
  rack (1.4.5) lib/rack/methodoverride.rb:21:in `call'
  rack (1.4.5) lib/rack/runtime.rb:17:in `call'
  activesupport (3.2.21) lib/active_support/cache/strategy/local_cache.rb:72:in `call'
  rack (1.4.5) lib/rack/lock.rb:15:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/static.rb:83:in `call'
  rack-cache (1.2) lib/rack/cache/context.rb:136:in `forward'
  rack-cache (1.2) lib/rack/cache/context.rb:245:in `fetch'
  rack-cache (1.2) lib/rack/cache/context.rb:185:in `lookup'
  rack-cache (1.2) lib/rack/cache/context.rb:66:in `call!'
  rack-cache (1.2) lib/rack/cache/context.rb:51:in `call'
  railties (3.2.21) lib/rails/engine.rb:484:in `call'
  railties (3.2.21) lib/rails/application.rb:231:in `call'
  rack (1.4.5) lib/rack/content_length.rb:14:in `call'
  rack (1.4.5) lib/rack/handler/webrick.rb:59:in `service'
  /usr/share/ruby/webrick/httpserver.rb:138:in `service'
  /usr/share/ruby/webrick/httpserver.rb:94:in `run'
  /usr/share/ruby/webrick/server.rb:295:in `block in start_thread'

**Comment by yourlin** [comment]
Environment:
  Redmine version                2.6.0.stable.13818
  Ruby version                   2.0.0-p353 (2013-11-22) [x86_64-linux]
  Rails version                  3.2.21
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.7.14
  Git                            1.8.3.1
  Filesystem                     
Redmine plugins:
  clipboard_image_paste          1.9
  redmine_agile                  1.3.5
  redmine_banner                 0.1.0
  redmine_bootstrap_kit          0.1
  redmine_checklists             3.0.2
  redmine_ckeditor               1.0.16
  redmine_close_button           0.0.8
  redmine_code_review            0.6.4
  redmine_dashboard              3.0.0.dev0
  redmine_jquery_opentip         1.0.0
  redmine_lightbox2              0.0.5
  redmine_theme_changer          0.1.0
  redmine_work_time              0.2.16

**Comment by yourlin** [comment]
Opps, it seems I installed the version 3.0.0.dev0

**Comment by yourlin** [comment]
Now I removed the version 3.x and installed the v2.4.
It works fine.
