### ISSUE TITLE
Can remove dashboard v3

### ISSUE THREAD

**Issue by ChrisK28** [jgraichen/redmine_dashboard#81]
Hi,
I'm facing issue with dashboard plugin. However I know the root cause is me, but I don't know how to solve now .... (have to mention that I'm a rookie with redmine, linux and all this stuff).

I had the problem, that dashboard is showing nothing, it's a blank sheet all the time. No matter what I do. However, that's not the issue. The issue it, that I can't remove the plugin now. I still have the plug in visible with version "3.0.0dev" in the plugin menu of redmine

What I did:
1) I installed dashboard plugin in version v3, because I didn't notice that it isn't stable yet. 
2) After no function --> Blank pages. I tried to remove plugin with
sudo rake redmine:plugins:migrate NAME=redmine_dashboard VERSION=0 RAILS_ENV=production
sudo rm -rf redmine_dashboard
3) and restarted apache server (sudo service apache2 restart)

I redo this several times (because is was thinking about any type mistake) but no better result. Till last time the "Dashboard" link is missing at headline of redmine and project menu, but instead I have a "translation missing: de.rdb.menu.dashboards" link of dashboard. Link brings "Page not found" now ....
Plugin is still mentioned at "admin" --> "plugins".

Any advice to fix this or do I have to reinstall everything?

I'm using ubuntu server 14, Redmine 2.5.3, if information would be required. I don't know what kind of additional information could be helpful.

Thanks, Christoph

**Comment by jgraichen** [comment]
What application server are you using? Passenger or some other? Did you remove `redmine_dashboard` in the `plugins` directory?

I've never experienced something like that so unfortunately can only give little help.
