### ISSUE TITLE
Missing issue statuses as Columns

### ISSUE THREAD

**Issue by LaureSQI** [jgraichen/redmine_dashboard#83]
I have a redmine 2.6.1 installed on an internal server with some plugins including redmine_dashboard 2.5.0 
![image](https://cloud.githubusercontent.com/assets/11311773/6482034/a9a79b44-c262-11e4-8d75-1af8d3b3fa25.png)

My configuration includes multiple tracker types with different issue statuses depending on the tracker.
Here is the list of issue statuses :

For example I have :
* some "task" trackers that use the statuses 'New / In progress / Implemented / Rejected / Closed',
![image](https://cloud.githubusercontent.com/assets/11311773/6482141/804ed20c-c263-11e4-814f-ad9d9df6c784.png)
* some "component" trackers that use the statuses 'New / Relevant / Obsolete' 
![image](https://cloud.githubusercontent.com/assets/11311773/6482147/8e2bd7e4-c263-11e4-8438-66bc20baf7e8.png)
* and so on ...

**In the Dashboard tab of my project I don't have all the issue statuses available.**
![image](https://cloud.githubusercontent.com/assets/11311773/6482239/421ce054-c264-11e4-9c27-c17e29e45981.png)
![image](https://cloud.githubusercontent.com/assets/11311773/6482244/49c85126-c264-11e4-80c1-e7b1309eccc5.png)

I can't see the statuses 'Closed' and 'Rejected' for example, it seems that the fact that there is more than one status marked as 'Issue closed' is generating this problem.
I tried to move the 'Closed' status at the bottom of the list of statuses (in the administration) in order to get it in my dashboard but without success.

**Comment by jgraichen** [comment]
As of now all statuses that are marked as 'Issue closed' are combined into the 'Done' column. When you drop an issue on the 'Done' column you will be asked which status you want to apply.

As of now this cannot be changed but the next major version will have configurable column mappings.
