### ISSUE TITLE
Make fails on 3.0.0.dev0

### ISSUE THREAD

**Issue by DennisonWilliams** [jgraichen/redmine_dashboard#84]
Following the [instructions](https://github.com/jgraichen/redmine_dashboard/blob/master/README.md) when I get to the make section I get this from my system:
````
# make
mkdir -p assets/fonts
cp node_modules/font-awesome/fonts/*-webfont* assets/fonts
cp: cannot stat `node_modules/font-awesome/fonts/*-webfont*': No such file or directory
make: *** [fonts] Error 1
````

**Comment by jgraichen** [comment]
Thanks for notice. You need to install gems and node packages before running `make`. The referenced `make install` target does not longer exists. It should have given the following:
```
> make install
make: *** No rule to make target 'install'.  Stop.
```

I updated the README but please note that 3.0.0.dev is still not usable.

```
> bundle install
> npm install
```
