### ISSUE TITLE
Nothing show in the board when I choose "View - Issue group by parent project"

### ISSUE THREAD

**Issue by yourlin** [jgraichen/redmine_dashboard#85]
When I choose "View - Issue group by parent project"

The titile bar can show the count of issues in each status,
but the board shows nothing.

![qq 20150312151731](https://cloud.githubusercontent.com/assets/6930286/6613692/87a93394-c8cb-11e4-9d0e-4b301f1e30c6.png)

**Comment by jgraichen** [comment]
I'm sorry I cannot replicate your issue. Can you please check if anything appears in your log file and that no other filter is inferring. I also need to know what Redmine version you are running.

**Comment by jgraichen** [comment]
Also you seems to have checked `Group by parent task`. Is this only a translation issue or do you mean `parent project`?

**Comment by yourlin** [comment]
Sorry for the translation issue, it's "Group by parent task"

Now I figure out how did it happen.
This issue caused by the theme which one is not default.
I am using the theme named "basecamp-with-icon"
When I changed it to "default", it works fine.

**Comment by yourlin** [comment]
sorry, for my mistake, i thought "it works fine"
In fact, there are still something wrong in the function.

**Comment by budokaiman** [comment]
I am also seeing this issue, it seems easily reproducible on v2.6.1 by doing the following:
1. Have project with two versions V1 and V2
2. Open dashboard, viewing V1 tasks
3. Change grouping to "by parent task"
4. Change version to V2

**Comment by budokaiman** [comment]
I can also confirm the behaviour exists in 2.7.0

**Comment by jgraichen** [comment]
Can you please check if this bug is still present in the latest 2.11.0 version?
