### ISSUE TITLE
Uncaught error in dashboard.js

### ISSUE THREAD

**Issue by colinexl** [jgraichen/redmine_dashboard#87]
Hello,

I'm running Redmine 3.0 and installed this plugin using master branch. Went through the build steps and found this:

Uncaught ReferenceError: Rdb is not defined

I tried making with production and received the following error:

```
ubuntu@ip-172-31-8-111:/usr/share/redmine/plugins/redmine_dashboard$ make min # production
mkdir -p assets/fonts
cp node_modules/font-awesome/fonts/*-webfont* assets/fonts
bundle exec sass -rbourbon -Inode_modules -Iapp/assets --style compressed app/assets/main.sass assets/main.min.css
NODE_PATH=.:app/assets NODE_ENV=production node node_modules/.bin/browserify -i jquery -t coffeeify --extension=".coffee" -t browserify-data -t envify app/assets/main.coffee | node node_modules/.bin/uglifyjs -m -c > assets/main.min.js 2> /dev/null
make: *** [assets/main.min.js] Error 8
```

So I instead used the development instead.

**Comment by jgraichen** [comment]
Make reports an error. Was there any more console output? Or can you try removing ` 2> /dev/null` from the Makefile line and try again.

Current master branch compiles locally and on CI.

**Comment by colinexl** [comment]
That helped, found out that uglifyjs wasn't installed for some reason. After npm install uglifyjs it worked! Thank you.

**Comment by colinexl** [comment]
Hello, to clarify, I was able to make the production build, however I'm still receiving:

```Uncaught ReferenceError: Rdb is not defined``` in dashboards.js line 185.

Thanks,
Colin Zhu

**Comment by jgraichen** [comment]
Are you running Redmine in `RAILS_ENV=production`? Please also check what `<script>` tags are emitted on the page and that Redmine has copied the compiled assets into it's `public/...` directory. It should do that when starting.
