### ISSUE TITLE
Redmine_dashboard and Bitnami Redmine 3.0.1

### ISSUE THREAD

**Issue by KingBain** [jgraichen/redmine_dashboard#88]
Had to modify the gem file and run bundle install to make this plugin work 

```
source 'https://rubygems.org'
# Gems required by redmine_dashboard

gem 'haml'
gem 'guard-rspec'
gem 'transifex-ruby-fork-jg'
gem 'inifile'

group :development do
  gem 'guard-rspec'
  gem 'transifex-ruby-fork-jg', require: false
  gem 'inifile', require: false
end

group :test do
  gem 'rspec', '~> 2.0'
  gem 'rspec-rails'
  gem 'poltergeist'
  gem 'database_cleaner'
  gem 'fuubar'

  # for redmine on travis CI
  gem 'test-unit'
end
```

**Comment by uirapuru** [comment]
Do you get something like this?

```
uirapuru@server:/usr/share/redmine$ bundle exec rake redmine:plugins:migrate RAILS_ENV=production
You cannot specify the same gem twice with different version requirements.
You specified: test-unit (~> 3.0) and test-unit (>= 0)
```

**Comment by jgraichen** [comment]
Try to use `bundle install --without development test` or completely remove the gem groups. All these warnings are only related to gems for development and testing (of the plugin). They are not needed for production use.

As the plugin has to work and therefore be tested with multiple Redmine versions I have to specify some gems I need in newer version or some that are not part of all supported Redmine versions. Additionally they change with new releases. Again, they are not needed for production.
