### ISSUE TITLE
Dashboard doesn't show anything

### ISSUE THREAD

**Issue by renancmfreitas** [jgraichen/redmine_dashboard#91]
Hi,

I installed Redmine_Dashboard, but when I choose "Dashboard" at my project to view de dashboards, nothing appears. 
I am using a Bitnami Redmine V.2.6.3. 

Here what's going on: http://i.imgur.com/pRbCuf6.png
No error, but no data or filters too. Someone please can help me?

Thank you

**Comment by jgraichen** [comment]
You have probably installed current development version 3.0 without building the assets. Please follow the [install instructions for current stable v2](https://github.com/jgraichen/redmine_dashboard/tree/stable-v2#install) or the [compile instructions for 3.0-dev (experimental)](https://github.com/jgraichen/redmine_dashboard#install-v3-pre-alpha).

Does this solves you issue?
