### ISSUE TITLE
Doesn't work in redmine 3.0.2

### ISSUE THREAD

**Issue by cheoAlejo** [jgraichen/redmine_dashboard#92]
It doesn't work in redmine 3.0.2 bitnami Ubuntu 14.04. Once I installed the plugin redmine stops working:
![2015-05-14 01_27_14-we re sorry but something went wrong 500](https://cloud.githubusercontent.com/assets/10518807/7627149/726c0756-f9d9-11e4-84e5-533cfe5b0bb0.png)
I followed the steps given:

    cd /opt/bitnami/apps/redmine/htdocs/plugins
    git clone https://github.com/jgraichen/redmine_dashboard.git
    cd redmine_dashboard
    git checkout v2.6.1
    bundle install

And I restarted redmine, I even rebooted the machine.

**Comment by jgraichen** [comment]
Please attach the Redmine production log file otherwise it's impossible to help. Please also note that using an appliance is not supported as they have crude and different setups.

Please also see #88, #58, #24 and #11.

**Comment by cheoAlejo** [comment]
Thanks for the response. Yes Im moving to a full installation of redmine.

**Comment by cheoAlejo** [comment]
I finally got it to work, this plugin is awesome.

**Comment by springerin** [comment]
i'm having the same problem..what solution worked for you?
