### ISSUE TITLE
Empty board on parent project

### ISSUE THREAD

**Issue by cheoAlejo** [jgraichen/redmine_dashboard#96]
Greetings, perhaps i'm missing something.
I have a project with subprojects, the dashboard at the parent project is empty.

![2015-06-03 10_39_47-financiero - delfin redmine](https://cloud.githubusercontent.com/assets/10518807/7964560/f7b1e480-09dd-11e5-976f-5009295d27e5.png)
_screenshot with the board grouped by project_

![2015-06-03 10_40_04-financiero - delfin redmine](https://cloud.githubusercontent.com/assets/10518807/7964576/0c52ab90-09de-11e5-95b2-204b43769885.png)

Nothing in the error logs.

Dashboard v2.6.1
Redmine 2.6.5 full installation
Ubuntu 14.04

**Comment by cheoAlejo** [comment]
The problem seems to be related to versions.
The parent project doesn't have versions, but one of the subprojects has 2 versions.

As the parent project doesn't have versions, the filter above the parent project dashboard doesn't show up, and therefore there's no way to apply the "All versions" filter.

![2015-06-03 18_20_48-rss - delfin redmine](https://cloud.githubusercontent.com/assets/10518807/7973632/567dae24-0a1d-11e5-8c99-01aa966fabde.png)


I created a version to the parent project and didn't assign any issues to it, and **the dashboard works fine**.

![2015-06-03 18_28_06-financiero - delfin redmine](https://cloud.githubusercontent.com/assets/10518807/7973739/93941dec-0a1e-11e5-8e0f-f31b632e9a5d.png)


Also, if none of the subprojects have versions, the dashboard works just fine.

**Comment by jgraichen** [comment]
Version 2.7.0 will correctly show the the version filter on a parent project without own versions. This will allow you to view "all" versions like on a single project.

Please report if it does not solve your problem.
