### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by hemaldesai** [jgraichen/redmine_dashboard#97]
Hello,

I have installed redmine 2.6.5 bitnami stack on windows 8.1 64 bit. When i am trying to install redmine_dashboard i am getting error "cannot load such file -- haml". 

step followed :

1. bundle install --without development test
2. ruby bin/rake redmine:plugins NAME=redmine_dashboard-stable-v2 RAILS_ENV=production

Could you please help me on this?

Thanks
Hemal

**Comment by jgraichen** [comment]
Please see #58 and #11.
