### ISSUE TITLE
Dashboard does not show any issues for subprojects

### ISSUE THREAD

**Issue by janekska** [jgraichen/redmine_dashboard#99]
I have project with two subprojects. For both of them dashboard works well, but I could not get whole "picture" for parent project, while it is possible in Ghant chart.

**Comment by jgraichen** [comment]
Is this similar to #96?

**Comment by janekska** [comment]
Uh, thanks - it was my fault!
I missed that "Include subprojects" option in options filter list at right side.

It is working as expected!
